MSM4G: msm4g_lib.h File Reference
msm4g_lib.h File Reference
The declarations of the functions.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <float.h>
#include <assert.h>
#include "msm4g_types.h"
#include "msm4g_bases.h"
#include "msm4g_constants.h"
Macros
#define MSM4G_MAX3(A, B, C) (((A)>(B))?(((A)>(C))?(A):(C)):(((B)>(C))?(B):(C)))
#define MSM4G_MIN2(A, B) (((A)<(B)) ? (A) : (B))
Functions
void msm4g_tic ()
Matlab-style tic() function.
double msm4g_toc ()
Matlab-style toc() function.
double msm4g_tictocmanager (int push)
Help function for tic/toc functionality.
double msm4g_potential_energy (Simulation *simulation)
Calculate potential energy of the simulation.
void msm4g_stencil (Simulation *simulation, int level)
Calculates the stencils.
Simulation * msm4g_simulation_new (char *datafile, SimulationBox *box, Boolean periodic, int order, double abar, int mu, int L, int Mx, int My, int Mz)
Creates a new simulation object.
void msm4g_simulation_run (Simulation *simulation)
Executes a simulation.
void msm4g_simulation_save (Simulation *simulation, FILE *fp)
Save simulation object into a stream Simulation objects and its child objects are saved into a file stream in YAML format.
void msm4g_simulation_delete (Simulation *simulation)
Deallocates a given simulation object.
void msm4g_anterpolation (Simulation *simulation)
Anterpolation.
void msm4g_restriction (Simulation *simulation, int l)
Restriction It performs restriction step from level l-1 to l where l is in the range [2, L].
void msm4g_prolongation (Simulation *simulation)
Prolongation Execute all prolongation steps.
void msm4g_interpolation (Simulation *simulation)
Interpolation This function calculates the long-range acceralation of the particles by interpolating the grid potentials on the finest level and the B-Splines.
void msm4g_grid_print (AbstractGrid *grid)
Print the content of grid to the stdout.
void msm4g_grid_destroy (AbstractGrid **grid)
Deallocates a grid.
AbstractGrid * msm4g_grid_dense_new (int nx, int ny, int nz, double hx, double hy, double hz)
A DenseGrid constructor.
void msm4g_grid_dense_setElement (AbstractGrid *grid, int i, int j, int k, double value)
Sets a value to a specific coordinate of the DenseGrid.
double msm4g_grid_dense_getElement (AbstractGrid *grid, int i, int j, int k)
Gets a single element from a DenseGrid object.
double msm4g_grid_dense_innerProduct (AbstractGrid *grid1, AbstractGrid *grid2)
Calculates inner product of two dense grids.
double msm4g_grid_dense_sum (AbstractGrid *grid)
Sum of grid elements.
void msm4g_grid_dense_add (AbstractGrid *grid1, AbstractGrid *grid2)
Add two dense grids It implements the following sum: grid1 = grid1 + grid2.
void msm4g_grid_dense_reset (AbstractGrid *grid, double value)
Reset all values in the grid to the given value.
void msm4g_grid_dense_destroy (AbstractGrid **densegrid)
Deconstructor for the DenseGrid object.
void msm4g_grid_potential (AbstractGrid *stencil, AbstractGrid *gridmass, AbstractGrid *gridpotential)
Calculate grid-to-grid interaction to get grid potentials.
double msm4g_smoothing_gama (double rho, int nu)
Even-powered Softener.
double msm4g_smoothing_gamaprime (double rho, int nu)
Derivative of even-powered softener.
double msm4g_kernel (int l, int L, double r, double a, double beta, int nu)
Compute splitting kernels.
double msm4g_force_short (LinkedList *binlist, double threshold, Simulation *simulation)
Short-range force and potential energy calculation.
double msm4g_force_short_withinBin (Bin *bin, double threshold, Simulation *simulation)
Calculates short-range forces and potential energy.
double msm4g_force_short_betweenBin (Bin *bin, Bin *neigbor, double threshold, Simulation *simulation)
Calculates short-range interactions between two set of particles.
double msm4g_force_short_particlePair (Particle *particleI, Particle *particleJ, double threshold, Simulation *simulation)
Short-range force and potential energy for a pair of particles.
void msm4g_d3vector_set (D3Vector *d3vector, double x, double y, double z)
Sets the elements of a 3-element vector.
void msm4g_d3vector_daxpy (D3Vector *z, D3Vector *x, double a, D3Vector *y)
Implemention of z = x + a*y.
double msm4g_d3vector_norm (D3Vector *x)
The Euclidean norm of a 3-dimensional double vector.
double msm4g_d3vector_normsquare (D3Vector *x)
Calculates norm square of a vector.
void msm4g_d3vector_print (D3Vector *x)
Print a 3D vector.
void msm4g_i3vector_set (I3Vector *i3vector, int x, int y, int z)
Sets the elements of a 3-element vector.
void msm4g_i3vector_copy (I3Vector *to, I3Vector from)
Copy the content of a I3Vector to another.
Boolean msm4g_i3vector_isequal (I3Vector *x, I3Vector *y)
Compare two 3D integer vector.
void msm4g_i3vector_print (I3Vector *x)
Print a 3D int vector in [d,d,d] format.
LinkedList * msm4g_linkedlist_new ()
Creates an empty linked list.
void msm4g_linkedlist_add (LinkedList *list, void *data)
Adds a data pointer to a linked list.
void * msm4g_linkedlist_get (LinkedList *list, int index)
Get a specific element from a linked list.
int msm4g_linkedlist_size (LinkedList *list)
Determines the number of elements in a linked list.
void msm4g_linkedlist_destroy (LinkedList *list)
Deaallocate the linked list.
void msm4g_linkedlist_destroyWithData (LinkedList *list)
Destroy the linked list including the data.
Particle * msm4g_particle_empty ()
Allocates a brand-new empty Particle.
Particle * msm4g_particle_new (double mass, double x, double y, double z)
Creates a new Particle with given properties.
Particle ** msm4g_particle_rand (int n)
Creates an array of andom particles.
Particle * msm4g_particle_read (const char *filename, int *N)
Load the Particle configuration from a text file.
Particle * msm4g_particle_reset (Particle *Particle)
Sets all of the properties of a Particle to zero value.
void msm4g_particle_print (Particle *Particle)
Print the properties of a Particle.
void msm4g_particle_printlist (LinkedList *Particlelist)
Print all particles in a linked list.
void msm4g_particle_destroy (Particle *Particle)
Deallocates a single Particle object.
void msm4g_particle_destroyarray (Particle **Particlearray, int length)
Deallocates an array of Particle objects.
SimulationBox * msm4g_box_new ()
Create a unit cube for simulation.
SimulationBox * msm4g_box_newCube (double location, double width)
Creates a cube.
void msm4g_box_update (SimulationBox *box, LinkedList *particles, double margin, double h, double p)
Update the simulation box for a given list of particles.
void msm4g_box_translate (SimulationBox *box, LinkedList *particles, D3Vector delta)
Translate the box and the particles by delta vector.
void msm4g_box_translateToOrigin (SimulationBox *box, LinkedList *particles)
Translate the box and the particles so that the location of box is zero vector.
void msm4g_box_print (SimulationBox *box)
Print the details of the simulation box.
void msm4g_box_destroy (SimulationBox *box)
Deallocates the simulation box.
Bin * msm4g_bin_new (int nx, int ny, int nz)
Create a new Bin for given index.
LinkedList * msm4g_bin_generate (SimulationBox *box, Particle *particles, int n, double width, Boolean periodic)
Generate bins for a given simulation box and Particle list.
void msm4g_bin_findneighbors (LinkedList *binlist, int minbinindexx, int minbinindexy, int minbinindexz, int maxbinindexx, int maxbinindexy, int maxbinindexz, Boolean periodic)
Find the neigbhors of each Bin.
Bin * msm4g_bin_searchByIndex (LinkedList *binlist, int index)
Returns the bin with given index vector.
void msm4g_bin_print (Bin *bin)
Print the contents of a bin.
void msm4g_bin_printlist (LinkedList *binlist)
Print all bins in a linked list.
void msm4g_bin_destroy (LinkedList *binlist)
Deallocates a bin list.
void msm4g_acceleration (double *a, double *r, int n, int d, double *m, double G)
void msm4g_energy (double *pot, double *kin, double *tot, double *r, double *v, int n, int d, double *m, double G)
void msm4g_forwardeuler (double *r, double *v, double *a, double dt, int n, int d, double *m, double G)
void msm4g_leapfrog (double *r, double *v, double *a, double *a1, double dt, int n, int d, double *m, double G)
Leap-Frog time-integration scheme.
void msm4g_print_energy (double pot0, double kin0, double tot0, double pot, double kin, double tot)
void msm4g_zeros (double *x, int n)
int msm4g_math_cantor (int *x, int n)
n-degree generalized Cantor pairing function.
int msm4g_math_factorial (int n)
Factorial function.
double * msm4g_util_omegaprime (int mu, int p)
Calculates Quasi-interpolation coefficients.
double msm4g_util_norm (double x[], int n)
L2-norm of a vector.
double msm4g_util_diffnorm (double x[], double y[], int n)
L2-norm of x-y.
void msm4g_util_gausssolver (int n, double *A, double *y)
Solve Ax=y by Gaussian elimination.
int msm4g_util_face_enumerate (int n, SimulationParameters *sp)
Enumerate grid points on the surface of a cubic grid.
double msm4g_util_choose_beta (double aL)
Determines Ewald's splitting parameter.
double msm4g_util_calculate_c (int k, double M, int nu)
Calculates the coefficients needed for interpolation at (L+1)th level Refer eq:calpha in the manuscript.
double msm4g_util_nchoosek (int n, int k)
Implements the binomial function.
double msm4g_util_jn (int nu, int k)
Implements the restriction operator.
Detailed Description
The declarations of the functions.
Definition in file msm4g_lib.h.
Macro Definition Documentation
#define MSM4G_MAX3 (A, B, C) (((A)>(B))?(((A)>(C))?(A):(C)):(((B)>(C))?(B):(C)))
Definition at line 18 of file msm4g_lib.h.
Referenced by msm4g_simulation_new().
#define MSM4G_MIN2 (A, B) (((A)<(B)) ? (A) : (B))
Definition at line 19 of file msm4g_lib.h.
Referenced by msm4g_simulation_new().
Function Documentation
void msm4g_tic ()
Matlab-style tic() function.
Definition at line 7 of file msm4g_lib.c.
References msm4g_tictocmanager().
Referenced by msm4g_simulation_run().
double msm4g_toc ()
Matlab-style toc() function.
Returns
elapsed time in seconds.
Definition at line 11 of file msm4g_lib.c.
References msm4g_tictocmanager().
Referenced by msm4g_simulation_run().
double msm4g_tictocmanager (int push)
Help function for tic/toc functionality.
Parameters
[in] push If not zero, it means tic() is called, otherwise toc() is called.
Returns
elapsed-time in seconds if push argument is non-zero.
Definition at line 15 of file msm4g_lib.c.
Referenced by msm4g_tic(), and msm4g_toc().
double msm4g_potential_energy (Simulation * simulation)
Calculate potential energy of the simulation.
Parameters
[in,out] simulation The object storing everything related with the simulation
Returns
Potential energy of the system
Definition at line 31 of file msm4g_lib.c.
References SimulationParameters::a, SimulationParameters::beta, Simulation::box, Simulation::gridmass, Simulation::gridpotential, AbstractGrid::innerProduct, SimulationParameters::L, Particle::m, msm4g_kernel(), msm4g_smoothing_gama(), MYPI, SimulationParameters::N, SimulationParameters::nu, Simulation::output, Simulation::parameters, Simulation::particles, Particle::potential_short_real, SimulationOutput::potentialEnergyLongRange, SimulationOutput::potentialEnergyShortRange, SimulationOutput::potentialEnergyTotal, SimulationBox::wx, SimulationBox::wy, and SimulationBox::wz.
Referenced by msm4g_simulation_run().
void msm4g_stencil (Simulation * simulation, int level)
Calculates the stencils.
This function calculates the stencil values corresponding to the specified level. It modifies the stencil located in the simulation object.
Parameters
[in] simulation Simulation object
[in] level Level in the range [1,L+1]. l = 1 corresponds to the lowest level stencil, whereas l = L + 1 is for Fourier stencil.
Todo:
Make necessary changes for vacuum boundary. For now it is tailor-made for periodic
Definition at line 105 of file msm4g_lib.c.
References SimulationParameters::a, SimulationParameters::beta, Simulation::box, LinkedListElement::data, SimulationParameters::face_i, SimulationParameters::face_j, SimulationParameters::face_k, LinkedList::head, AbstractGrid::hx, AbstractGrid::hy, AbstractGrid::hz, SimulationOutput::kernelEvaluationsComputed, SimulationOutput::kernelEvaluationsNeeded, SimulationOutput::kernelHatEvaluationsComputed, SimulationOutput::kernelHatEvaluationsNeeded, KMAX, SimulationParameters::L, msm4g_kernel(), msm4g_linkedlist_add(), msm4g_linkedlist_destroyWithData(), msm4g_linkedlist_new(), msm4g_util_calculate_c(), msm4g_util_face_enumerate(), SimulationParameters::mu, MYPI, LinkedListElement::next, SimulationParameters::nu, AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::output, Simulation::parameters, SimulationParameters::periodic, PMAX, AbstractGrid::setElement, Simulation::stencil, TOL_DIRECT, SimulationParameters::wprime, SimulationBox::wx, SimulationBox::wy, and SimulationBox::wz.
Referenced by msm4g_simulation_run(), msm4g_unit_test_18(), and msm4g_unit_test_19().
Simulation* msm4g_simulation_new (char * datafile, SimulationBox * box, Boolean periodic, int order, double abar, int mu, int L, int Mx, int My, int Mz)
Creates a new simulation object.
It reads particles from a file and builds a simulation object.
Parameters
[in] datafile Filename containing the particles
[in] box Simulation box object
[in] periodic If true, periodics boundary condition applies
[in] order Order of accuracy. It can only be 4 or 6
[in] abar Relative-cutoff
[in] mu Quasi-interpolation parameter
[in] L Number of levels. If it is set to zero, it is calculated automatically.
[in] Mx Number of grids along x-axis. If it is set to zero, it is calculated automatically.
[in] My Number of grids along y-axis. If it is set to zero, it is calculated automatically.
[in] Mz Number of grids along z-axis. If it is set to zero, it is calculated automatically.
Todo:
Change "4 or 6" statement when it is needed.
Returns
Simulation object
Todo:
These are slightly different from the manuscript which uses Mxmin = -M/2, Mxmax = M/2 - 1
Definition at line 355 of file msm4g_lib.c.
References SimulationParameters::a, SimulationParameters::abar, SimulationParameters::beta, Simulation::box, Simulation::gridmass, Simulation::gridpotential, SimulationParameters::h, SimulationParameters::hx, SimulationParameters::hy, SimulationParameters::hz, SimulationParameters::L, msm4g_grid_dense_new(), MSM4G_MAX3, MSM4G_MIN2, msm4g_particle_read(), msm4g_util_choose_beta(), SimulationParameters::mu, SimulationParameters::Mx, SimulationParameters::Mxmax, SimulationParameters::Mxmin, SimulationParameters::My, SimulationParameters::Mymax, SimulationParameters::Mymin, SimulationParameters::Mz, SimulationParameters::Mzmax, SimulationParameters::Mzmin, SimulationParameters::N, SimulationParameters::nbarx, SimulationParameters::nbary, SimulationParameters::nbarz, SimulationParameters::nu, Simulation::output, Simulation::parameters, Simulation::particles, SimulationParameters::periodic, Simulation::stencil, SimulationBox::wx, SimulationBox::wy, and SimulationBox::wz.
Referenced by main(), msm4g_unit_test_11(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), and msm4g_unit_test_9().
void msm4g_simulation_run (Simulation * simulation)
Executes a simulation.
Parameters
[in] simulation Pointer to the simulation object
Definition at line 455 of file msm4g_lib.c.
References SimulationParameters::a, Particle::acc_long, Particle::acc_short, Particle::acc_total, AbstractGrid::add, Simulation::box, Simulation::gridmass, Simulation::gridpotential, SimulationParameters::L, msm4g_anterpolation(), msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_force_short(), msm4g_grid_potential(), msm4g_interpolation(), msm4g_potential_energy(), msm4g_prolongation(), msm4g_restriction(), msm4g_stencil(), msm4g_tic(), msm4g_toc(), msm4g_util_omegaprime(), SimulationParameters::mu, SimulationParameters::N, SimulationParameters::nu, Simulation::output, Simulation::parameters, Simulation::particles, SimulationParameters::periodic, Simulation::stencil, SimulationOutput::time_anterpolation, SimulationOutput::time_energy, SimulationOutput::time_grid_to_grid, SimulationOutput::time_interpolation, SimulationOutput::time_omegaprime, SimulationOutput::time_prolongation, SimulationOutput::time_restriction, SimulationOutput::time_short_direct, SimulationOutput::time_stencil, SimulationOutput::time_stencil_fourier, and SimulationParameters::wprime.
Referenced by main(), msm4g_unit_test_21(), msm4g_unit_test_22(), and msm4g_unit_test_23().
void msm4g_simulation_save (Simulation * simulation, FILE * fp)
Save simulation object into a stream Simulation objects and its child objects are saved into a file stream in YAML format.
Parameters
[in] simulation Simulation object
[in] fp Pointer to the stream.
Definition at line 534 of file msm4g_lib.c.
References SimulationParameters::a, SimulationParameters::abar, SimulationParameters::beta, Simulation::box, SimulationParameters::h, SimulationParameters::hx, SimulationParameters::hy, SimulationParameters::hz, SimulationOutput::kernelEvaluationsComputed, SimulationOutput::kernelEvaluationsNeeded, SimulationOutput::kernelHatEvaluationsComputed, SimulationOutput::kernelHatEvaluationsNeeded, SimulationParameters::L, SimulationParameters::mu, SimulationParameters::Mx, SimulationParameters::Mxmax, SimulationParameters::Mxmin, SimulationParameters::My, SimulationParameters::Mymax, SimulationParameters::Mymin, SimulationParameters::Mz, SimulationParameters::Mzmax, SimulationParameters::Mzmin, SimulationParameters::N, SimulationParameters::nbarx, SimulationParameters::nbary, SimulationParameters::nbarz, SimulationParameters::nu, AbstractGrid::nx, Simulation::output, Simulation::parameters, SimulationParameters::periodic, SimulationOutput::potentialEnergyLongRange, SimulationOutput::potentialEnergyShortRange, SimulationOutput::potentialEnergyTotal, Simulation::stencil, SimulationOutput::time_anterpolation, SimulationOutput::time_energy, SimulationOutput::time_grid_to_grid, SimulationOutput::time_interpolation, SimulationOutput::time_omegaprime, SimulationOutput::time_prolongation, SimulationOutput::time_restriction, SimulationOutput::time_short_direct, SimulationOutput::time_stencil, SimulationOutput::time_stencil_fourier, SimulationParameters::wprime, SimulationBox::wx, SimulationBox::wy, SimulationBox::wz, SimulationBox::x, SimulationBox::y, and SimulationBox::z.
Referenced by main().
void msm4g_simulation_delete (Simulation * simulation)
Deallocates a given simulation object.
Parameters
[in] simulation Pointer to the simulation object
Definition at line 620 of file msm4g_lib.c.
References Simulation::box, Simulation::gridmass, Simulation::gridpotential, SimulationParameters::L, msm4g_box_destroy(), msm4g_grid_destroy(), Simulation::output, Simulation::parameters, Simulation::particles, Simulation::stencil, and SimulationParameters::wprime.
Referenced by main(), msm4g_unit_test_11(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), and msm4g_unit_test_9().
void msm4g_anterpolation (Simulation * simulation)
Anterpolation.
Definition at line 638 of file msm4g_lib.c.
References Simulation::box, AbstractGrid::getElement, Simulation::gridmass, SimulationParameters::h, SimulationParameters::hx, SimulationParameters::hy, SimulationParameters::hz, SimulationBox::location, Particle::m, MAX_POLY_DEGREE, msm4g_bases_bspline(), SimulationParameters::Mx, SimulationParameters::My, SimulationParameters::Mz, SimulationParameters::N, SimulationParameters::nu, Simulation::parameters, Simulation::particles, SimulationParameters::periodic, Particle::r, AbstractGrid::setElement, and D3Vector::value.
Referenced by msm4g_simulation_run(), msm4g_unit_test_11(), msm4g_unit_test_16(), msm4g_unit_test_18(), and msm4g_unit_test_19().
void msm4g_restriction (Simulation * simulation, int l)
Restriction It performs restriction step from level l-1 to l where l is in the range [2, L].
Parameters
[in] simulation Simulation object
[in] l Level number in [2,L]
Definition at line 741 of file msm4g_lib.c.
References AbstractGrid::getElement, Simulation::gridmass, msm4g_util_jn(), SimulationParameters::nu, AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::parameters, and AbstractGrid::setElement.
Referenced by msm4g_simulation_run().
void msm4g_prolongation (Simulation * simulation)
Prolongation Execute all prolongation steps.
Parameters
[in] simulation Simulation object
Todo:
Clean it
Definition at line 787 of file msm4g_lib.c.
References AbstractGrid::add, AbstractGrid::getElement, Simulation::gridpotential, SimulationParameters::L, msm4g_util_jn(), SimulationParameters::nu, AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::parameters, and AbstractGrid::setElement.
Referenced by msm4g_simulation_run().
void msm4g_interpolation (Simulation * simulation)
Interpolation This function calculates the long-range acceralation of the particles by interpolating the grid potentials on the finest level and the B-Splines.
Parameters
[in] simulation the object containing all information about the simulation
Definition at line 843 of file msm4g_lib.c.
References Particle::acc_long, AbstractGrid::getElement, Simulation::gridpotential, SimulationParameters::hx, SimulationParameters::hy, SimulationParameters::hz, msm4g_bases_bspline(), msm4g_bases_bsplineprime(), SimulationParameters::Mx, SimulationParameters::My, SimulationParameters::Mz, SimulationParameters::N, SimulationParameters::nu, Simulation::parameters, Simulation::particles, SimulationParameters::periodic, Particle::r, and D3Vector::value.
Referenced by msm4g_simulation_run(), and msm4g_unit_test_18().
void msm4g_grid_print (AbstractGrid * grid)
Print the content of grid to the stdout.
Parameters
[in] grid A grid to be printed.
Definition at line 900 of file msm4g_lib.c.
References AbstractGrid::getElement, AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
void msm4g_grid_destroy (AbstractGrid ** grid)
Deallocates a grid.
This function first calls the destructor of the grid, and then deallocates itself.
Parameters
[in,out] grid The grid to be allocated.
Definition at line 910 of file msm4g_lib.c.
Referenced by msm4g_simulation_delete(), and msm4g_unit_test_10().
AbstractGrid* msm4g_grid_dense_new (int nx, int ny, int nz, double hx, double hy, double hz)
A DenseGrid constructor.
It create a new DenseGrid structure to hold all the values on the grid nodes. The internal data structure is later dealocated in the msm4g_grid_dense_destroy() function.
Parameters
[in] nx The number of nodes along x-axis.
[in] ny The number of nodes along y-axis.
[in] nz The number of nodes along z-axis.
[in] hx The lattice spacing along x-axis.
[in] hy The lattice spacing along y-axis.
[in] hz The lattice spacing along z-axis.
Returns
A new DenseGrid structure.
Definition at line 918 of file msm4g_lib.c.
References AbstractGrid::add, AbstractGrid::constructor, DenseGrid::data, AbstractGrid::destructor, AbstractGrid::getElement, AbstractGrid::hx, AbstractGrid::hy, AbstractGrid::hz, AbstractGrid::innerProduct, msm4g_grid_dense_add(), msm4g_grid_dense_destroy(), msm4g_grid_dense_getElement(), msm4g_grid_dense_innerProduct(), msm4g_grid_dense_new(), msm4g_grid_dense_reset(), msm4g_grid_dense_setElement(), msm4g_grid_dense_sum(), AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, AbstractGrid::reset, AbstractGrid::setElement, and AbstractGrid::sum.
Referenced by msm4g_grid_dense_new(), msm4g_simulation_new(), and msm4g_unit_test_10().
void msm4g_grid_dense_setElement (AbstractGrid * grid, int i, int j, int k, double value)
Sets a value to a specific coordinate of the DenseGrid.
With this function, one can change a single element of DenseGrid.
Parameters
[in,out] grid A DenseGrid whose element is changed.
[in] i The coordinate in the x-axis.
[in] j The coordinate in the y-axis.
[in] k The coordinate in the z-axis.
[in] value The new value of the element.
Definition at line 945 of file msm4g_lib.c.
References DenseGrid::data, AbstractGrid::nx, and AbstractGrid::ny.
Referenced by msm4g_grid_dense_new().
double msm4g_grid_dense_getElement (AbstractGrid * grid, int i, int j, int k)
Gets a single element from a DenseGrid object.
Returns the (i,j,k) element of the dense matrix.
Parameters
[in] grid The AbstractGrid object.
[in] i The coordinate in the x-axis.
[in] j The coordinate in the y-axis.
[in] k The coordinate in the z-axis.
Returns
The value of the element corresponding to (i,j,k) coordinate.
Definition at line 954 of file msm4g_lib.c.
References DenseGrid::data, AbstractGrid::nx, and AbstractGrid::ny.
Referenced by msm4g_grid_dense_new().
double msm4g_grid_dense_innerProduct (AbstractGrid * grid1, AbstractGrid * grid2)
Calculates inner product of two dense grids.
Inner product of two dense grid is the sum of pairwise multiplications of the dense grids.
Parameters
[in] grid1 First dense grid
[in] grid2 Second dense grid
Returns
the inner product of the grids.
Definition at line 962 of file msm4g_lib.c.
References DenseGrid::data, AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
Referenced by msm4g_grid_dense_new().
double msm4g_grid_dense_sum (AbstractGrid * grid)
Sum of grid elements.
Parameters
[in] grid A dense grid
Returns
sum of grid elements
Definition at line 978 of file msm4g_lib.c.
References DenseGrid::data, AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
Referenced by msm4g_grid_dense_new(), msm4g_unit_test_21(), msm4g_unit_test_22(), and msm4g_unit_test_23().
void msm4g_grid_dense_add (AbstractGrid * grid1, AbstractGrid * grid2)
Add two dense grids It implements the following sum: grid1 = grid1 + grid2.
Parameters
[in,out] grid1 First dense grid
[in] grid2 Second dense grid
Definition at line 988 of file msm4g_lib.c.
References DenseGrid::data, AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
Referenced by msm4g_grid_dense_new().
void msm4g_grid_dense_reset (AbstractGrid * grid, double value)
Reset all values in the grid to the given value.
This function resets the elements of the internal dense matrix to the given value.
Parameters
[in,out] grid A grid to be reset.
[in] value The grid is to be reset to value.
Definition at line 1002 of file msm4g_lib.c.
References AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
Referenced by msm4g_grid_dense_new().
void msm4g_grid_dense_destroy (AbstractGrid ** densegrid)
Deconstructor for the DenseGrid object.
Internal data structure used in a DenseGrid object is deallocated by using this function. The deallocation of the grid object itself is handled in msm4g_grid_destroy() function.
Parameters
[in,out] densegrid A pointer to the DenseGrid structure to be deallocated.
Definition at line 1012 of file msm4g_lib.c.
References DenseGrid::data.
Referenced by msm4g_grid_dense_new().
void msm4g_grid_potential (AbstractGrid * stencil, AbstractGrid * gridmass, AbstractGrid * gridpotential)
Calculate grid-to-grid interaction to get grid potentials.
Todo:
Write down the LateX formula
Parameters
[in] stencil stencil
[in] gridmass gridmass
[in,out] gridpotential gridpotential
Definition at line 1019 of file msm4g_lib.c.
References AbstractGrid::nx, AbstractGrid::ny, and AbstractGrid::nz.
Referenced by msm4g_simulation_run(), msm4g_unit_test_18(), and msm4g_unit_test_19().
double msm4g_smoothing_gama (double rho, int nu)
Even-powered Softener.
\[ \gamma(\rho) = \left\{ \begin{array}{ll} \tau_\nu(\rho^2), & 0 \le \rho \le 1, \\ 1/\rho, & \rho \ge 1. \end{array} \right. \]
where
\[ \tau_\nu(s) = \sum_{k=0}^{\nu-1}{-1/2\choose k}(s-1)^k \]
Parameters
[in] rho Input value
[in] nu order of accuracy
Returns
Returns \(\gamma(\rho) \)
Definition at line 1080 of file msm4g_lib.c.
Referenced by msm4g_force_short_particlePair(), msm4g_kernel(), msm4g_potential_energy(), msm4g_unit_test_14(), and msm4g_unit_test_8().
double msm4g_smoothing_gamaprime (double rho, int nu)
Derivative of even-powered softener.
Parameters
[in] rho Input value
[in] nu order of accuracy
Returns
Returns \(\gamma'(\rho) \)
Definition at line 1094 of file msm4g_lib.c.
Referenced by msm4g_force_short_particlePair(), msm4g_unit_test_14(), and msm4g_unit_test_8().
double msm4g_kernel (int l, int L, double r, double a, double beta, int nu)
Compute splitting kernels.
Todo:
Include the equations in LateX format
Parameters
[in] l Level in the range of [0,L+1]
[in] L Number of levels.
[in] r Distance value
[in] a Absolute cutoff
[in] beta Splitting parameter
[in] nu Order
Returns
the value of the kernel function
Definition at line 1110 of file msm4g_lib.c.
References msm4g_smoothing_gama(), and MYPI.
Referenced by msm4g_potential_energy(), and msm4g_stencil().
double msm4g_force_short (LinkedList * binlist, double threshold, Simulation * simulation)
Short-range force and potential energy calculation.
For each bin in the linked list
Calculate the short-range forces between the particles in the bin
Calculate the pairwise force between the neighbor bins.
Parameters
[in,out] binlist The list of bins.
[in] threshold The range of the short-range force.
[in] simulation Simulation object.
Returns
Total short-range potential energy in the list of bins.
Definition at line 1134 of file msm4g_lib.c.
References Bin::cantorindex, LinkedListElement::data, Bin::ghostOf, LinkedList::head, Bin::isGhost, msm4g_force_short_betweenBin(), msm4g_force_short_withinBin(), Bin::neighbors, LinkedListElement::next, and shortRangeInteractionCount.
Referenced by msm4g_simulation_run(), msm4g_unit_test_15(), and msm4g_unit_test_9().
double msm4g_force_short_withinBin (Bin * bin, double threshold, Simulation * simulation)
Calculates short-range forces and potential energy.
Given a list of particles, it calculates the short-range force interactions within the particles.
Parameters
[in,out] bin The bin containing the particles.
[in] threshold Cut-off parameter.
[in] simulation Simulation object.
Returns
Short-range potential energy in the Bin.
Definition at line 1188 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, msm4g_force_short_particlePair(), LinkedListElement::next, and Bin::particles.
Referenced by msm4g_force_short().
double msm4g_force_short_betweenBin (Bin * bin, Bin * neigbor, double threshold, Simulation * simulation)
Calculates short-range interactions between two set of particles.
it calculates the short-range interactions between the particles in the bin and the neighborbin.
Parameters
[in,out] bin Current bin.
[in,out] neigbor Neigbor bin.
[in] threshold Cut-off parameter.
[in] simulation Simulation object.
Returns
Short-range potential energy between the bins.
Definition at line 1209 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, msm4g_force_short_particlePair(), LinkedListElement::next, and Bin::particles.
Referenced by msm4g_force_short().
double msm4g_force_short_particlePair (Particle * particleI, Particle * particleJ, double threshold, Simulation * simulation)
Short-range force and potential energy for a pair of particles.
Parameters
[in,out] particleI The first particle.
[in,out] particleJ The second particle.
[in] threshold Cut-off parameter.
[in] simulation Simulation object.
Returns
Short-range potential energy.
Definition at line 1232 of file msm4g_lib.c.
References SimulationParameters::a, Particle::acc_short, Simulation::box, Particle::fshort, Particle::m, msm4g_d3vector_daxpy(), msm4g_d3vector_normsquare(), msm4g_smoothing_gama(), msm4g_smoothing_gamaprime(), SimulationParameters::nu, Simulation::parameters, SimulationParameters::periodic, Particle::potential_short_real, Particle::r, shortRangeInteractionCount, D3Vector::value, SimulationBox::wx, SimulationBox::wy, and SimulationBox::wz.
Referenced by msm4g_force_short_betweenBin(), and msm4g_force_short_withinBin().
void msm4g_d3vector_set (D3Vector * d3vector, double x, double y, double z)
Sets the elements of a 3-element vector.
The elements of a 3DVector is set to the given values of x,y, and z.
Parameters
[in,out] d3vector A pointer to a 3-element double vector.
[in] x The first element.
[in] y The second element.
[in] z The third element.
Definition at line 1311 of file msm4g_lib.c.
References D3Vector::value.
Referenced by msm4g_box_new(), msm4g_particle_reset(), and msm4g_unit_test_5().
void msm4g_d3vector_daxpy (D3Vector * z, D3Vector * x, double a, D3Vector * y)
Implemention of z = x + a*y.
A very simple DAXPY (BLAS) implementation. The first argument z, is the output. So it should be allocated before calling the function.
Parameters
[in,out] z The z vector in z = x + a*y.
[in] x The x vector.
[in] a The scalar in front of y vector.
[in] y The y vector.
Definition at line 1317 of file msm4g_lib.c.
References D3Vector::value.
Referenced by msm4g_force_short_particlePair(), and msm4g_unit_test_5().
double msm4g_d3vector_norm (D3Vector * x)
The Euclidean norm of a 3-dimensional double vector.
This function simple calculates the Euclidean norm a vector:
\[ ||x||=\sqrt{\sum_{i=1}^3 x^2_i} \]
Example:
* D3Vector x;
* double norm;
*
* msm4g_d3vector_set(&x,3.0,0.0,4.0);
* norm = msm4g_d3vector_norm(&x)
* // norm variable is 5.0 now.
*
Parameters
[in] x A 3-dimensional double vector.
Returns
The norm of the vector.
Definition at line 1324 of file msm4g_lib.c.
References msm4g_d3vector_normsquare().
Referenced by msm4g_unit_test_5().
double msm4g_d3vector_normsquare (D3Vector * x)
Calculates norm square of a vector.
Parameters
[in] x 3-element double vector x.
Returns
Returns \(||x||^2 \)
Example:
* D3Vector x;
* double normsquare;
*
* msm4g_d3vector_set(&x,3.0,0.0,4.0);
* normsquare = msm4g_d3vector_normsquare(&x)
* // norm variable is 25.0 now.
*
Definition at line 1328 of file msm4g_lib.c.
References D3Vector::value.
Referenced by msm4g_d3vector_norm(), and msm4g_force_short_particlePair().
void msm4g_d3vector_print (D3Vector * x)
Print a 3D vector.
Parameters
[in] x A 3-dimensional double vector.
Definition at line 1337 of file msm4g_lib.c.
References D3Vector::value.
void msm4g_i3vector_set (I3Vector * i3vector, int x, int y, int z)
Sets the elements of a 3-element vector.
The elements of a 3D-integer vector is set to the given values of x,y, and z.
Parameters
[in,out] i3vector A pointer to a 3-element integer vector.
[in] x The first element.
[in] y The second element.
[in] z The third element.
Definition at line 1344 of file msm4g_lib.c.
References I3Vector::value.
void msm4g_i3vector_copy (I3Vector * to, I3Vector from)
Copy the content of a I3Vector to another.
Parameters
[in,out] to The updated vector.
[in] from The source vector.
Definition at line 1350 of file msm4g_lib.c.
References I3Vector::value.
Boolean msm4g_i3vector_isequal (I3Vector * x, I3Vector * y)
Compare two 3D integer vector.
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
True if the vectors are same, false otherwise.
Definition at line 1356 of file msm4g_lib.c.
References I3Vector::value.
void msm4g_i3vector_print (I3Vector * x)
Print a 3D int vector in [d,d,d] format.
Parameters
[in] x A 3-element integer array
Definition at line 1367 of file msm4g_lib.c.
References I3Vector::value.
LinkedList* msm4g_linkedlist_new ()
Creates an empty linked list.
This function allocates an empty linked list and returns its pointer to the caller. A linked list created with this function should be deallocated at the end of the program by calling msm4g_linkedlist_destroy function.
In order to add data to the newly creaded linked list, one may use msm4g_linkedlist_add function.
Returns
The pointer of the new linked list.
Definition at line 1382 of file msm4g_lib.c.
References LinkedList::head, and LinkedList::tail.
Referenced by msm4g_bin_generate(), msm4g_bin_new(), msm4g_stencil(), msm4g_unit_test_1(), msm4g_unit_test_2(), msm4g_unit_test_3(), msm4g_unit_test_5(), and msm4g_unit_test_all().
void msm4g_linkedlist_add (LinkedList * list, void * data)
Adds a data pointer to a linked list.
This function is used to add a data pointer to the end of a linked list. Please note that, only the pointer to the data is copied into the linked list. The actual data content should be prepared before calling this function. And for the same reason, when the linked list is deallocated, the original data is not touched. Deallocation of the data should be handled separately.
Parameters
[in,out] list The linked list to be updated.
[in] data Pointer to the data.
Definition at line 1390 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, LinkedListElement::next, LinkedListElement::prev, and LinkedList::tail.
Referenced by msm4g_bin_findneighbors(), msm4g_bin_generate(), msm4g_stencil(), msm4g_unit_test_1(), msm4g_unit_test_2(), msm4g_unit_test_3(), msm4g_unit_test_5(), and msm4g_unit_test_all().
void* msm4g_linkedlist_get (LinkedList * list, int index)
Get a specific element from a linked list.
In some situations, one may require to get a specific element from the linked list by giving its exact location in the list.
Parameters
[in] list The linked listed to be searched.
[in] index The zero-based index of the element.
Returns
The void pointer of the requested data. If there is no data, then NULL pointer is returned.
Definition at line 1409 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, and LinkedListElement::next.
Referenced by msm4g_unit_test_6(), and msm4g_unit_test_all().
int msm4g_linkedlist_size (LinkedList * list)
Determines the number of elements in a linked list.
By traversing from head element to the tail, this function counts the number of elements of a given linked list.
Parameters
[in] list The linked list whose size is to be determined.
Returns
The number of elements inside the linked list.
Definition at line 1371 of file msm4g_lib.c.
References LinkedList::head, and LinkedListElement::next.
Referenced by msm4g_bin_generate(), msm4g_unit_test_1(), msm4g_unit_test_6(), and msm4g_unit_test_all().
void msm4g_linkedlist_destroy (LinkedList * list)
Deaallocate the linked list.
Since the elements of a linked list are dynamically allocated, the linked list should be destroyed if it is not going to be used anymore. This function deallocates all the elements (`LinkedListElement') in the list.
Warning
This function does not deallocate the actual data pointed in the elements. This is the responsibility of the developer to track down the location of the actual data and deallocate it at the end of the program.
Parameters
[in,out] list The list to be deallocated.
Definition at line 1427 of file msm4g_lib.c.
References LinkedList::head, and LinkedListElement::next.
Referenced by msm4g_bin_destroy(), msm4g_linkedlist_destroyWithData(), msm4g_unit_test_1(), msm4g_unit_test_2(), msm4g_unit_test_3(), msm4g_unit_test_5(), and msm4g_unit_test_all().
void msm4g_linkedlist_destroyWithData (LinkedList * list)
Destroy the linked list including the data.
Almost the same with the function msm4g_linkedlist_destroy except that the data contained in the linked list elements are also deallocated.
Parameters
[in,out] list The list to be destroyed.
Definition at line 1439 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, msm4g_linkedlist_destroy(), and LinkedListElement::next.
Referenced by msm4g_stencil().
Particle* msm4g_particle_empty ()
Allocates a brand-new empty Particle.
This functions is the only place inside which a memory allocation is carried to create a new Particle. This function holds a static Particle index to keep track the newly born particles.
Returns
A pointer to the newly allocated Particle structure.
Definition at line 1876 of file msm4g_lib.c.
References Particle::acc_short, Particle::flong, Particle::fshort, Particle::index, Particle::m, Particle::potential_short_real, Particle::r, Particle::v, and D3Vector::value.
Referenced by msm4g_particle_new(), and msm4g_particle_rand().
Particle* msm4g_particle_new (double mass, double x, double y, double z)
Creates a new Particle with given properties.
Parameters
[in] mass The mass of the Particle.
[in] x x-axis of the location.
[in] y y-axis of the location.
[in] z z-axis of the location.
Returns
The pointer of the newly allocated Particle.
Definition at line 1898 of file msm4g_lib.c.
References Particle::m, msm4g_particle_empty(), Particle::r, and D3Vector::value.
Particle** msm4g_particle_rand (int n)
Creates an array of andom particles.
This function creates an array of Particle structures whose properties are randomly created in the range [0-1]. Therefore, the particles reside in three-dimensional unit cube.
Returns
The pointer to the first element of the allocated array.
Definition at line 1822 of file msm4g_lib.c.
References Particle::flong, Particle::fshort, Particle::m, msm4g_particle_empty(), Particle::r, Particle::v, and D3Vector::value.
Referenced by msm4g_unit_test_5().
Particle* msm4g_particle_read (const char * filename, int * N)
Load the Particle configuration from a text file.
Parameters
[in] filename The name of the file containing the Particle properties.
[in,out] N Number of particles
Returns
Pointer to a particle array
Definition at line 1841 of file msm4g_lib.c.
References Particle::index, Particle::m, Particle::r, Particle::v, and D3Vector::value.
Referenced by msm4g_simulation_new(), msm4g_unit_test_4(), and msm4g_unit_test_6().
Particle* msm4g_particle_reset (Particle * Particle)
Sets all of the properties of a Particle to zero value.
Sometimes, it is desirable to use already created particles, but with different properties. Then this function becomes handy, to reset its properties to zero value.
Parameters
[in,out] Particle The Particle whose properties to be reset.
Returns
The pointer of the input Particle.
Definition at line 1813 of file msm4g_lib.c.
References Particle::flong, Particle::fshort, Particle::m, msm4g_d3vector_set(), Particle::r, and Particle::v.
Referenced by msm4g_unit_test_1(), and msm4g_unit_test_4().
void msm4g_particle_print (Particle * Particle)
Print the properties of a Particle.
The mass, location, and other properties if it has any are printed to the standard output.
Parameters
[in] Particle The Particle whose properties are to be printed.
Definition at line 1908 of file msm4g_lib.c.
References Particle::r, and D3Vector::value.
Referenced by msm4g_particle_printlist().
void msm4g_particle_printlist (LinkedList * Particlelist)
Print all particles in a linked list.
This functions assumes that the linked list elements point to Particle data types.
Parameters
[in] Particlelist The list of particles to be printed.
Definition at line 1913 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, msm4g_particle_print(), and LinkedListElement::next.
void msm4g_particle_destroy (Particle * Particle)
Deallocates a single Particle object.
Parameters
[in,out] Particle The Particle to be deallocated.
Definition at line 1928 of file msm4g_lib.c.
void msm4g_particle_destroyarray (Particle ** Particlearray, int length)
Deallocates an array of Particle objects.
Parameters
[in,out] Particlearray The array to be deallocates.
[in] length The length of the array.
Definition at line 1933 of file msm4g_lib.c.
Referenced by msm4g_unit_test_5().
SimulationBox* msm4g_box_new ()
Create a unit cube for simulation.
Allocates a new simulation box whose location is at the origin
Warning
It is the responsibility of the caller to deallocate the box by using msm4g_box_destory function.
Todo:
Make sure that the width is of the form 2^k * h for some k.
Returns
The new simulation box.
Definition at line 1460 of file msm4g_lib.c.
References SimulationBox::location, msm4g_d3vector_set(), and SimulationBox::width.
Referenced by main(), msm4g_box_newCube(), and msm4g_unit_test_5().
SimulationBox* msm4g_box_newCube (double location, double width)
Creates a cube.
Parameters
[in] location Location of the cube
[in] width Width of the cube
Returns
Reference to the simulation box object
Definition at line 1468 of file msm4g_lib.c.
References SimulationBox::location, msm4g_box_new(), D3Vector::value, SimulationBox::width, SimulationBox::wx, SimulationBox::wy, SimulationBox::wz, SimulationBox::x, SimulationBox::y, and SimulationBox::z.
Referenced by msm4g_unit_test_11(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), and msm4g_unit_test_9().
void msm4g_box_update (SimulationBox * box, LinkedList * particles, double margin, double h, double p)
Update the simulation box for a given list of particles.
It creates a rectangular there dimensional box to include all of the particles given in the argument. The width of the box is also enlarged margin percent in each dimension to give some slack to the particles so that they will stay in the box after time integration.
The width of the box is arranged to be a multiple of lattice spacing h.
The degree of the base polynomials is also needed to make sure that there is enough extra padding around the boundary.
Todo:
If a Particle escapes from the box, the box should be updated. But there is a question of how to keep the interior grid points intact. As soon as the box is enlarged, new grid points should be created. MSM may start from scratch whenever the box is updated, but it seems quite waste of time.
Parameters
[in,out] box The rectangular simulation box.
[in] particles The list of particles.
[in] margin The box is enlarged margin percent (0.10 default).
[in] h Lattice spacing in the finest level grid.
[in] p The degree of the base polynomials. p should be odd and larger than 0.
Definition at line 1481 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, SimulationBox::location, LinkedListElement::next, Particle::r, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_5().
void msm4g_box_translate (SimulationBox * box, LinkedList * particles, D3Vector delta)
Translate the box and the particles by delta vector.
Parameters
[in,out] box The simulation box.
[in,out] particles The list of particles.
[in] delta Translation amoun.
Definition at line 1549 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, SimulationBox::location, LinkedListElement::next, Particle::r, and D3Vector::value.
Referenced by msm4g_box_translateToOrigin().
void msm4g_box_translateToOrigin (SimulationBox * box, LinkedList * particles)
Translate the box and the particles so that the location of box is zero vector.
This function is equivalant to msm4g_box_translate with delta vector is opposite to the location of the box.
Parameters
[in,out] box The simulation box.
[in,out] particles The list of particles.
Definition at line 1568 of file msm4g_lib.c.
References SimulationBox::location, msm4g_box_translate(), and D3Vector::value.
void msm4g_box_print (SimulationBox * box)
Print the details of the simulation box.
The location, width and other features of the simulation box is printed to the standard output.
Parameters
[in] box The box whose information is to be printed.
Definition at line 1576 of file msm4g_lib.c.
References SimulationBox::location, D3Vector::value, and SimulationBox::width.
void msm4g_box_destroy (SimulationBox * box)
Deallocates the simulation box.
The simulation box can be deallocated by using this function.
Parameters
[in] box The simulation box to be deallocated.
Definition at line 1587 of file msm4g_lib.c.
Referenced by msm4g_simulation_delete(), and msm4g_unit_test_5().
Bin* msm4g_bin_new (int nx, int ny, int nz)
Create a new Bin for given index.
Todo:
Give more information
Definition at line 1591 of file msm4g_lib.c.
References Bin::cantorindex, Bin::ghostOf, Bin::isGhost, msm4g_linkedlist_new(), msm4g_math_cantor(), Bin::neighbors, Bin::nx, Bin::ny, Bin::nz, and Bin::particles.
Referenced by msm4g_bin_generate().
LinkedList* msm4g_bin_generate (SimulationBox * box, Particle * particles, int n, double binwidth, Boolean periodic)
Generate bins for a given simulation box and Particle list.
The particles are supposed to be contained in the box. And also the the location of the simulation box is expected to be [0,0,0]. If not the caller should translate the box and the particles so that the location of the box is at the origin.
Parameters
[in] box The simulation box.
[in] particles The list of particles.
[in] n Number of particles
[in] width The width of the bins.
[in] periodic Is there a periodic boundary?
Returns
The list of allocated bins.
Todo:
Be carefull, bin indexes can be negative here.
Definition at line 1606 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, Bin::isGhost, msm4g_bin_findneighbors(), msm4g_bin_new(), msm4g_bin_searchByIndex(), msm4g_linkedlist_add(), msm4g_linkedlist_new(), msm4g_linkedlist_size(), msm4g_math_cantor(), LinkedListElement::next, Bin::particles, Particle::r, and D3Vector::value.
Referenced by msm4g_simulation_run(), msm4g_unit_test_15(), msm4g_unit_test_6(), and msm4g_unit_test_9().
void msm4g_bin_findneighbors (LinkedList * binlist, int minbinindexx, int minbinindexy, int minbinindexz, int maxbinindexx, int maxbinindexy, int maxbinindexz, Boolean periodic)
Find the neigbhors of each Bin.
For each Bin in the linked list.
Check if there is a Bin in one of the 26 neighbor cubes.
If there is a bin, then add it to the neighbor list.
Parameters
[in,out] binlist The linked list of Bin's.
[in] minbinindexx Minimum possible bin index along x-axis.
[in] minbinindexy Minimum possible bin index along y-axis.
[in] minbinindexz Minimum possible bin index along z-axis.
[in] maxbinindexx Minimum possible bin index along x-axis.
[in] maxbinindexy Minimum possible bin index along y-axis.
[in] maxbinindexz Minimum possible bin index along z-axis.
[in] periodic Is there a periodic boundary?
Definition at line 1676 of file msm4g_lib.c.
References Bin::cantorindex, LinkedListElement::data, Bin::ghostOf, LinkedList::head, Bin::isGhost, msm4g_bin_searchByIndex(), msm4g_linkedlist_add(), msm4g_math_cantor(), Bin::neighbors, LinkedListElement::next, Bin::nx, Bin::ny, Bin::nz, and Bin::particles.
Referenced by msm4g_bin_generate().
Bin* msm4g_bin_searchByIndex (LinkedList * binlist, int index)
Returns the bin with given index vector.
This function loops over binlist to find a bin with same index information given in the argument.
Parameters
[in] binlist The list of bins.
[in] index Cantor index
Returns
The pointer to the selected bin. Returns NULL if there is no such bin.
Definition at line 1753 of file msm4g_lib.c.
References Bin::cantorindex, LinkedListElement::data, LinkedList::head, and LinkedListElement::next.
Referenced by msm4g_bin_findneighbors(), and msm4g_bin_generate().
void msm4g_bin_print (Bin * bin)
Print the contents of a bin.
Parameters
[in] bin The bin to be printed.
Definition at line 1768 of file msm4g_lib.c.
References Bin::cantorindex, LinkedListElement::data, LinkedList::head, Bin::isGhost, Bin::neighbors, LinkedListElement::next, Bin::nx, Bin::ny, Bin::nz, and Bin::particles.
Referenced by msm4g_bin_printlist().
void msm4g_bin_printlist (LinkedList * binlist)
Print all bins in a linked list.
Parameters
[in] binlist The list of bin's.
Definition at line 1788 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, msm4g_bin_print(), and LinkedListElement::next.
void msm4g_bin_destroy (LinkedList * binlist)
Deallocates a bin list.
For each Bin in the list
Deallocate the neighbor list (without data)
Deallocate the Particle list (without data)
Deallocate the bin list
Parameters
[in,out] binlist The linked list of Bin's.
Definition at line 1797 of file msm4g_lib.c.
References LinkedListElement::data, LinkedList::head, Bin::isGhost, msm4g_linkedlist_destroy(), Bin::neighbors, LinkedListElement::next, and Bin::particles.
Referenced by msm4g_simulation_run(), msm4g_unit_test_15(), msm4g_unit_test_6(), and msm4g_unit_test_9().
void msm4g_acceleration (double * a, double * r, int n, int d, double * m, double G)
Definition at line 1943 of file msm4g_lib.c.
References msm4g_zeros().
Referenced by msm4g_forwardeuler(), and msm4g_leapfrog().
void msm4g_energy (double * pot, double * kin, double * tot, double * r, double * v, int n, int d, double * m, double G)
Definition at line 1963 of file msm4g_lib.c.
void msm4g_forwardeuler (double * r, double * v, double * a, double dt, int n, int d, double * m, double G)
Definition at line 1450 of file msm4g_lib.c.
References msm4g_acceleration().
void msm4g_leapfrog (double * r, double * v, double * a, double * a1, double dt, int n, int d, double * m, double G)
Leap-Frog time-integration scheme.
Parameters
[in,out] r The locations of the particles.
[in,out] v The velocities of the particles.
[in,out] a The acceleration of the particles.
[in,out] a1 The acceleration of the particles on half-step time.
[in] dt The timestep.
[in] n The number of particles.
[in] d The spatial dimension.
[in] m The mass of the particles.
[in] G the gravitational constant.
Definition at line 1998 of file msm4g_lib.c.
References msm4g_acceleration().
void msm4g_print_energy (double pot0, double kin0, double tot0, double pot, double kin, double tot)
Definition at line 1992 of file msm4g_lib.c.
void msm4g_zeros (double * x, int n)
Definition at line 2009 of file msm4g_lib.c.
Referenced by msm4g_acceleration().
int msm4g_math_cantor (int * x, int n)
n-degree generalized Cantor pairing function.
This method is the direct implementation of the n-degree generalized Cantor pairing function defined in Theorem 2.1 in Lisi, M. (2007). Some remarks on the Cantor pairing function. Le Matematiche, 62(1), 5565.
\[ <x_1,\ldots,x_2> = \sum_{h=1}^n\left\{ \frac{1}{h!}\prod_{j=0}^{h-1} \left[ \left(\sum_{i=1}^hx_i\right)+j\right] \right\} \]
Parameters
[in] x An integer vector in N^n.
[in] n The dimension.
Returns
The output of n-degree generalized Cantor pairing function.
Definition at line 2015 of file msm4g_lib.c.
References msm4g_math_factorial().
Referenced by msm4g_bin_findneighbors(), msm4g_bin_generate(), msm4g_bin_new(), and msm4g_unit_test_7().
int msm4g_math_factorial (int n)
Factorial function.
Parameters
[in] n A natural number.
Returns
factorial of n.
Definition at line 2034 of file msm4g_lib.c.
Referenced by msm4g_math_cantor(), and msm4g_unit_test_7().
double* msm4g_util_omegaprime (int mu, int p)
Calculates Quasi-interpolation coefficients.
Calculates the coefficients (referred as omegaprime in doi:10.1063/1.4943868) required in Quasi-interpolation. They depend on the order of B-Spline and some adjustable parameter mu.
The output of this function is used to build the stencils. Large mu means more accurate interpolation but at the same it increases the cost.
The callee is responsible to deallocate the array when it is no longer needed.
Todo:
Quasi-interpolation coefficients can only be determined for p=4 (Cubic) and p=6 (Quintic) B-Splines. It should be written in more generic way to cover higher order B-Splines.
Parameters
[in] mu Quasi-interpolation parameter
[in] p Order of B-Spline. It can be 4 (Cubic) and 6 (Quintic) only.
Returns
Quasi-interpolation coefficient array of size mu + p/2 + 1.
Definition at line 2044 of file msm4g_lib.c.
References msm4g_bases_bspline(), msm4g_util_diffnorm(), msm4g_util_gausssolver(), and msm4g_util_norm().
Referenced by msm4g_simulation_run(), msm4g_unit_test_12(), msm4g_unit_test_18(), and msm4g_unit_test_19().
double msm4g_util_norm (double x[], int n)
L2-norm of a vector.
Parameters
[in] x input vector
[in] n size of the input vector
Returns
L2-norm of the vector x
Definition at line 2229 of file msm4g_lib.c.
Referenced by msm4g_unit_test_15(), and msm4g_util_omegaprime().
double msm4g_util_diffnorm (double x[], double y[], int n)
L2-norm of x-y.
Parameters
[in] x first vector
[in] y second vector
[in] n size of the vectors
Returns
L2-norm of x-y
Definition at line 2237 of file msm4g_lib.c.
Referenced by msm4g_unit_test_15(), and msm4g_util_omegaprime().
void msm4g_util_gausssolver (int n, double * A, double * y)
Solve Ax=y by Gaussian elimination.
This solver is very simple featuring:
Does not use any pivoting.
Overwrites the matrix A and vector y.
At the end of the process, the right-hand side vector y becomes the solution.
Parameters
[in] n size of the system
[in] A matrix of size n by n
[in,out] y right hand-size vector of size n. It is also the solution.
Definition at line 2244 of file msm4g_lib.c.
Referenced by msm4g_util_omegaprime().
int msm4g_util_face_enumerate (int n, SimulationParameters * sp)
Enumerate grid points on the surface of a cubic grid.
Consider a cube centered at the origin and with size of 2n x 2n x 2n. The task is to enumerate the grid points on the surface of the cube.
Parameters
[in] n Size of the cube is 2n x 2n x 2n
[in] sp SimulationParameters object.
Returns
the number of grid points on the cube surface
Definition at line 2266 of file msm4g_lib.c.
References SimulationParameters::face_i, SimulationParameters::face_j, SimulationParameters::face_k, and FACE_MAXLEN.
Referenced by msm4g_stencil().
double msm4g_util_choose_beta (double aL)
Determines Ewald's splitting parameter.
Determines beta parameter such that erfc(beta * aL)/aL is very small
Todo:
Elaborate the scheme used in the function.
Parameters
[in] aL Cutoff at the coarsest grid
Returns
Ewald's splitting parameter beta
Definition at line 2320 of file msm4g_lib.c.
Referenced by msm4g_simulation_new(), and msm4g_unit_test_17().
double msm4g_util_calculate_c (int k, double M, int nu)
Calculates the coefficients needed for interpolation at (L+1)th level Refer eq:calpha in the manuscript.
Parameters
[in] k wavenumber in Fourier transform
[in] M The number of grid points
[in] nu Order of interpolation
Returns
value of the coefficient
Definition at line 2341 of file msm4g_lib.c.
References msm4g_bases_bspline(), and MYPI.
Referenced by msm4g_stencil().
double msm4g_util_nchoosek (int n, int k)
Implements the binomial function.
Parameters
[in] n an integer
[in] k an integer
Returns
nchoosek(n,k)
Definition at line 2350 of file msm4g_lib.c.
Referenced by msm4g_util_jn().
double msm4g_util_jn (int nu, int k)
Implements the restriction operator.
Todo:
Put the formula
Parameters
[in] nu order of B-Splines
[in] k an integer
Definition at line 2363 of file msm4g_lib.c.
References msm4g_util_nchoosek().
Referenced by msm4g_prolongation(), msm4g_restriction(), and msm4g_unit_test_20().