MSM4G: msm4g_tests.c File Reference
msm4g_tests.c File Reference
The test functions to check the functionality of the MSM4G package.
#include "msm4g_lib.h"
#include "msm4g_tests.h"
Functions
int main ()
void msm4g_test_summary ()
Display the overall status of all tests.
void msm4g_test_assert (const char *name, int status)
Add a new test.
void msm4g_unit_test_all ()
Runs all tests.
Boolean msm4g_unit_test_1 ()
Checks the size() functionality of linked lists.
Boolean msm4g_unit_test_2 ()
Traversing the linked list from tail to head.
Boolean msm4g_unit_test_3 ()
Traversing the list from head to tail.
Boolean msm4g_unit_test_4 ()
Reading particle configurations from a text file.
Boolean msm4g_unit_test_5 ()
Creating a box surrounding the particles.
Boolean msm4g_unit_test_6 ()
Generating bins for the particles in eight.ini file.
Boolean msm4g_unit_test_7 ()
Testing Cantor pairing function.
Boolean msm4g_unit_test_8 ()
Testing smoothing functions.
Boolean msm4g_unit_test_9 ()
Short-range energy calculation test.
Boolean msm4g_unit_test_10 ()
Testing DenseGrid implementation.
Boolean msm4g_unit_test_11 ()
Testing anterpolation.
Boolean msm4g_unit_test_12 ()
Checks the correctness of Quasi-interpolation coefficients.
Boolean msm4g_unit_test_13 ()
Checks B-Spline implementation.
Boolean msm4g_unit_test_14 ()
Checks the implementation of even-powered softener.
Boolean msm4g_unit_test_15 ()
Checks short-range potential energy and force for periodic boundary.
Boolean msm4g_unit_test_16 ()
Checks anterpolation for periodic boundary condition.
Boolean msm4g_unit_test_17 ()
Checks the fitness of Ewald's Splitting Parameter.
Boolean msm4g_unit_test_18 ()
Checks finest level stencil and grid potentials.
Boolean msm4g_unit_test_19 ()
Checks the Fourier stencil (l=L+1) It calculates the Fourier stencil and compare with the previously calculated stencil for ChaNGa,N=8.
Boolean msm4g_unit_test_20 ()
Checks JN function.
Boolean msm4g_unit_test_21 ()
Checks the integrity of anterpolation and restriction steps This test uses the fact that the sum of particle masses should stay same after anterpolation and restriction steps. The same idea does not apply to prolongation steps.
Boolean msm4g_unit_test_22 ()
Checks potential energy of NaCl crystals.
Boolean msm4g_unit_test_23 ()
Checks potential energy of NaCl crystal for N=64 case.
Boolean msm4g_unit_test_24 ()
Variables
char testnames [100][64]
Boolean teststatus [100]
int testcount = 0
Detailed Description
The test functions to check the functionality of the MSM4G package.
This is probably the best place one can learn how to use the package. These test functions are used to check the outcomes of the functions by comparing with expected results.
Definition in file msm4g_tests.c.
Function Documentation
int main ()
Definition at line 15 of file msm4g_tests.c.
References msm4g_unit_test_all().
void msm4g_test_summary ()
Display the overall status of all tests.
Definition at line 18 of file msm4g_tests.c.
References testcount, testnames, and teststatus.
Referenced by msm4g_unit_test_all().
void msm4g_test_assert (const char * name, int status)
Add a new test.
Parameters
[in] name A short description for the test (64 chars)
[in] status Test status
Definition at line 33 of file msm4g_tests.c.
References testcount, testnames, and teststatus.
Referenced by msm4g_unit_test_1(), msm4g_unit_test_10(), msm4g_unit_test_11(), msm4g_unit_test_12(), msm4g_unit_test_13(), msm4g_unit_test_14(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_17(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_2(), msm4g_unit_test_20(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), msm4g_unit_test_3(), msm4g_unit_test_4(), msm4g_unit_test_5(), msm4g_unit_test_6(), msm4g_unit_test_7(), msm4g_unit_test_8(), and msm4g_unit_test_9().
void msm4g_unit_test_all ()
Runs all tests.
All test functions are sequentiall run and their results are printed to standard output. If one of the tests is failed, then the corresponding test information is printed to the standard error.
Definition at line 43 of file msm4g_tests.c.
References msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_get(), msm4g_linkedlist_new(), msm4g_linkedlist_size(), msm4g_test_summary(), msm4g_unit_test_1(), msm4g_unit_test_10(), msm4g_unit_test_11(), msm4g_unit_test_12(), msm4g_unit_test_13(), msm4g_unit_test_14(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_17(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_2(), msm4g_unit_test_20(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), msm4g_unit_test_24(), msm4g_unit_test_3(), msm4g_unit_test_4(), msm4g_unit_test_5(), msm4g_unit_test_6(), msm4g_unit_test_7(), msm4g_unit_test_8(), and msm4g_unit_test_9().
Referenced by main().
Boolean msm4g_unit_test_1 ()
Checks the size() functionality of linked lists.
Returns
true if the test is successful, false otherwise.
Definition at line 87 of file msm4g_tests.c.
References msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_linkedlist_size(), msm4g_particle_reset(), and msm4g_test_assert().
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_2 ()
Traversing the linked list from tail to head.
Using the prev pointer element in the LinkedListElement one can travel from the tail element to the head.
Returns
true if the test is successful, false otherwise.
Definition at line 109 of file msm4g_tests.c.
References LinkedListElement::data, Particle::m, msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_test_assert(), LinkedListElement::prev, and LinkedList::tail.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_3 ()
Traversing the list from head to tail.
Returns
true if the test is successful, false otherwise.
Definition at line 143 of file msm4g_tests.c.
References LinkedListElement::data, LinkedList::head, Particle::m, msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_test_assert(), and LinkedListElement::next.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_4 ()
Reading particle configurations from a text file.
The masses, locations and velocities of three particles are read from eight.ini file and compared to the true values. If there is a slight variation, the test returns with fail.
Returns
true if the test is successful, false otherwise.
Definition at line 177 of file msm4g_tests.c.
References Particle::m, msm4g_particle_read(), msm4g_particle_reset(), msm4g_test_assert(), Particle::r, Particle::v, and D3Vector::value.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_5 ()
Creating a box surrounding the particles.
Given a collection of particles, this test determines a rectangular simulation box surrounding all of them and compares the result with the expected box. In this example, 10 random particles are created in unit 3D cube. Then the location of one of them is set to [-1,-2,-3]. Another one is set to [1,2,3]. Given this configuration the location, and the width of the box shoould be [-1,-2,-3] and [2,4,6] respectively. But then a 0.5 margin is also used to enlarge the box. Then the new width should be [3,6,9]. The location should also be shifted so that the there is a margin on both minus and plus axis. So the new location is [-1.5,-3,-4.5]. At the end of the test, the calculated location and width is compared with the expecteds.
Returns
true if the test is successful, false otherwise.
Definition at line 229 of file msm4g_tests.c.
References SimulationBox::location, msm4g_box_destroy(), msm4g_box_new(), msm4g_box_update(), msm4g_d3vector_daxpy(), msm4g_d3vector_norm(), msm4g_d3vector_set(), msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_particle_destroyarray(), msm4g_particle_rand(), msm4g_test_assert(), Particle::r, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_6 ()
Generating bins for the particles in eight.ini file.
The flow of this test is as follows:
Loading the particles from eight.ini file
Creating a simulation box around the particles with 0.5 extra margin
Generating the bins
30  +----------+----------+----------+     Bin Width: 10
|   |          |  4       |          |
|   |          |   5      |          |     Particle Location
|   |          |    6     |          |     -------- --------
|   |          |          |          |     1        [15,15, 5]
20  +----------+----------+----------+     2        [15,12, 5]
|   |          |          |          |     3        [29, 2,25]
|   |          |     1    |          |     4        [12,26, 5]
|   |          |          |          |     5        [13,25, 5]
|   |          |     2    |          |     6        [14,24, 5]
10  +----------+----------+----------+
|   |          |          |          |     Bins
|   |          |          |          |     ----
|   |          |          |          |     i j k   Particles Neighbor Bins
|   |          |          |         3|     - - -   --------- -------------
0   +----------+----------+----------+     1 1 0   1,2       [1,2,0]
                                           2 0 2   3         none
    0----------10---------20---------30    1 2 0   4,5,6     [1,1,0]
       i=0         i=1         i=2
Returns
true if the test is successful, false otherwise.
Definition at line 283 of file msm4g_tests.c.
References Bin::cantorindex, SimulationBox::location, msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_linkedlist_get(), msm4g_linkedlist_size(), msm4g_particle_read(), msm4g_test_assert(), Bin::neighbors, Bin::particles, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_7 ()
Testing Cantor pairing function.
The test function is used to check the output of Cantor pairing function msm4g_math_cantor() applied to a 4x4 matrix. If the enumeration is not equal to the one below, the test returns false. The test also checks the output of msm4g_math_factorial() function for the integers, 0, 1, 2, 3, 4, and 5.
i/j j=0 j=1 j=2 j=4
i=0 0 1 3 6
i=1 2 4 7 11
i=2 5 8 12 17
i=3 9 13 18 24
Returns
true if the test is successful, false otherwise.
Definition at line 336 of file msm4g_tests.c.
References msm4g_math_cantor(), msm4g_math_factorial(), and msm4g_test_assert().
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_8 ()
Testing smoothing functions.
Checks the implementation of the smoothing functions and their derivatives on p=0.0 and p=1.0; The \(\gamma \) functions tested are msm4g_smoothing_C1(), msm4g_smoothing_C2(), and msm4g_smoothing_C3().
Returns
true if the test is successful, false otherwise.
Definition at line 365 of file msm4g_tests.c.
References msm4g_smoothing_gama(), msm4g_smoothing_gamaprime(), and msm4g_test_assert().
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_9 ()
Short-range energy calculation test.
The setup of the particles and the simulation box is the same with msm4g_unit_test_6(). This time short-range force and energy calculation is carried out.
The manually calculated short-range potential regarding to the setup is 1.51303181237454868855 which is compared to the calculated potential energy. If the relative error in the potential energy is greater than 1E-15, the test is failed.
Note
In this test, C1 gamma smoothing function msm4g_smoothing_C1() is used with cut-off parameter a=10.
Returns
true if the test is successful, false otherwise.
Definition at line 406 of file msm4g_tests.c.
References SimulationParameters::a, Particle::m, msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_box_newCube(), msm4g_force_short(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_test_assert(), SimulationParameters::N, Simulation::output, Simulation::parameters, Simulation::particles, Particle::potential_short_real, SimulationOutput::potentialEnergyShortRange, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_10 ()
Testing DenseGrid implementation.
This function tests the basic functionality of DenseGrid related functions.
Returns
true if the test is successful, false otherwise.
Definition at line 448 of file msm4g_tests.c.
References msm4g_grid_dense_new(), msm4g_grid_destroy(), msm4g_test_assert(), AbstractGrid::reset, and AbstractGrid::setElement.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_11 ()
Testing anterpolation.
In this test, 8 unit mass particles are created on the following locations. The degree of base polynomials is set to p=3. Then a simulation box is created with margin=0. Since p=3, an extra padding is added around the boundary as shown in the following figure. Then the anterpolation is run. Since Hermite nodal basis functions are used in the anterpolation, the grid masses on the 8 interior nodes will be 1, and the rest should be zero.
30  +----------+----------+----------+     Lattice spacing (h): 10
|   |          |          |          |
|   |          |          |          |     Particle Location
|   |          |          |          |     -------- --------
|   |          |          |          |     1        [10,10,10]
20  +----------O----------O----------+     2        [10,10,20]
|   |          |          |          |     3        [10,20,10]
|   |          |          |          |     4        [10,20,20]
|   |          |          |          |     5        [20,10,10]
|   |          |          |          |     6        [20,10,20]
10  +----------O----------O----------+     7        [20,20,10]
|   |          |          |          |     8        [20,20,20]
|   |          |          |          |
|   |          |          |          |
|   |          |          |          |
0   +----------+----------+----------+
    0----------10---------20---------30
Returns
true if the test is successful, false otherwise.
Definition at line 474 of file msm4g_tests.c.
References AbstractGrid::getElement, Simulation::gridmass, SimulationParameters::h, msm4g_anterpolation(), msm4g_box_newCube(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_test_assert(), SimulationParameters::Mx, SimulationParameters::My, SimulationParameters::Mz, AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::parameters, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_12 ()
Checks the correctness of Quasi-interpolation coefficients.
Checks the accuracy of quasi-interpolation coefficients explained in "The Journal of Chem. Physics 144, 114112 (2016); doi: 10.1063/1.4943868" The test calculates the coefficients for Cubic and Quintic B-Spline cases and compare them to the ones published in the Table I of the same article.
Returns
true if the test is successful, false otherwise.
Definition at line 512 of file msm4g_tests.c.
References msm4g_test_assert(), msm4g_util_omegaprime(), and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_13 ()
Checks B-Spline implementation.
To check the implementation, I compare the results of MSM implementation to the ones I previously obtained by using Mathematica'a BSpline function for which the domain is always [0,1] in contrast to [0,k] in MSM. The test is successful if the following relation holds for points u = k*i/8 where i=0,...,8 and k is either 4 (cubic) or 6 (quintic).
 MSM Implementation                  Mathematica
 ------------------                  -----------
 msm4g_bases_bspline     (k, u)   =    BSpline[k-1,u/k]
 msm4g_bases_bsplineprime(k, u)   =  D[BSpline[k-1,u/k]]/k
 where u is in [0,k] and k is the order of B-Spline.
Returns
true if the test is successful, false otherwise.
Definition at line 545 of file msm4g_tests.c.
References msm4g_bases_bspline(), msm4g_bases_bsplineprime(), msm4g_test_assert(), and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_14 ()
Checks the implementation of even-powered softener.
This test evaluates the softener and its derivative on \(\rho = \{0,1/2,1,3/2\} \) for \(\nu=\{2,3,4,5,6\} \) and compare the results with the hand-evaluated values.
Returns
true if the test is successful, false otherwise
Definition at line 594 of file msm4g_tests.c.
References msm4g_smoothing_gama(), msm4g_smoothing_gamaprime(), msm4g_test_assert(), and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_15 ()
Checks short-range potential energy and force for periodic boundary.
It calculates the short-range potential energy and force and compares them to the ones computed with the reference periodic MSM implementation.
Returns
true if the test is successful, false otherwise
Definition at line 627 of file msm4g_tests.c.
References SimulationParameters::a, Particle::acc_short, Simulation::box, Particle::m, msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_box_newCube(), msm4g_force_short(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_test_assert(), msm4g_util_diffnorm(), msm4g_util_norm(), SimulationParameters::N, Simulation::output, Simulation::parameters, Simulation::particles, Particle::potential_short_real, SimulationOutput::potentialEnergyShortRange, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_16 ()
Checks anterpolation for periodic boundary condition.
The test compares the grid mass calculated in the anterpolation phase with the reference MSM calculation on ChaNGa N=8 case.
Returns
true if the test is successful, false otherwise
Definition at line 694 of file msm4g_tests.c.
References AbstractGrid::getElement, Simulation::gridmass, msm4g_anterpolation(), msm4g_box_newCube(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_test_assert(), SimulationParameters::Mx, SimulationParameters::My, SimulationParameters::Mz, Simulation::parameters, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_17 ()
Checks the fitness of Ewald's Splitting Parameter.
Ewald's Splitting Parameter (beta) is chosen in such a way that erfc(beta*aL)/aL is very small by using msm4g_util_choose_beta function. This test verifies the outcomes by actually checking it.
Returns
true if the test is successful, false otherwise
Definition at line 735 of file msm4g_tests.c.
References msm4g_test_assert(), msm4g_util_choose_beta(), and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_18 ()
Checks finest level stencil and grid potentials.
It calculates the first level stencil and grid potentials and compares them with the ones obtained by the reference MSM periodic implementation.
Returns
true if the test is successful, false otherwise
Definition at line 751 of file msm4g_tests.c.
References Particle::acc_long, AbstractGrid::getElement, Simulation::gridmass, Simulation::gridpotential, AbstractGrid::innerProduct, msm4g_anterpolation(), msm4g_box_newCube(), msm4g_grid_potential(), msm4g_interpolation(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_stencil(), msm4g_test_assert(), msm4g_util_omegaprime(), AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::parameters, Simulation::particles, Simulation::stencil, teststatus, and SimulationParameters::wprime.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_19 ()
Checks the Fourier stencil (l=L+1) It calculates the Fourier stencil and compare with the previously calculated stencil for ChaNGa,N=8.
Returns
true if the test is successful, false otherwise
Definition at line 863 of file msm4g_tests.c.
References AbstractGrid::getElement, Simulation::gridmass, Simulation::gridpotential, AbstractGrid::innerProduct, msm4g_anterpolation(), msm4g_box_newCube(), msm4g_grid_potential(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_stencil(), msm4g_test_assert(), msm4g_util_omegaprime(), AbstractGrid::nx, AbstractGrid::ny, AbstractGrid::nz, Simulation::parameters, Simulation::stencil, teststatus, and SimulationParameters::wprime.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_20 ()
Checks JN function.
Returns
true if the test is successful, false otherwise
Definition at line 940 of file msm4g_tests.c.
References false, msm4g_test_assert(), msm4g_util_jn(), and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_21 ()
Checks the integrity of anterpolation and restriction steps This test uses the fact that the sum of particle masses should stay same after anterpolation and restriction steps. The same idea does not apply to prolongation steps.
Returns
true if the test is successful, false otherwise
Definition at line 959 of file msm4g_tests.c.
References Simulation::gridmass, SimulationParameters::L, Particle::m, msm4g_box_newCube(), msm4g_grid_dense_sum(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_simulation_run(), msm4g_test_assert(), SimulationParameters::N, Simulation::output, Simulation::parameters, Simulation::particles, SimulationOutput::potentialEnergyTotal, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_22 ()
Checks potential energy of NaCl crystals.
Returns
true if the test is successful, false otherwise
Definition at line 989 of file msm4g_tests.c.
References Simulation::gridmass, SimulationParameters::L, Particle::m, msm4g_box_newCube(), msm4g_grid_dense_sum(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_simulation_run(), msm4g_test_assert(), SimulationParameters::N, Simulation::output, Simulation::parameters, Simulation::particles, SimulationOutput::potentialEnergyTotal, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_23 ()
Checks potential energy of NaCl crystal for N=64 case.
Returns
true if the test is successful, false otherwise
Definition at line 1019 of file msm4g_tests.c.
References Simulation::gridmass, SimulationParameters::L, Particle::m, msm4g_box_newCube(), msm4g_grid_dense_sum(), msm4g_simulation_delete(), msm4g_simulation_new(), msm4g_simulation_run(), msm4g_test_assert(), SimulationParameters::N, Simulation::output, Simulation::parameters, Simulation::particles, SimulationOutput::potentialEnergyTotal, and teststatus.
Referenced by msm4g_unit_test_all().
Boolean msm4g_unit_test_24 ()
Definition at line 1051 of file msm4g_tests.c.
References teststatus.
Referenced by msm4g_unit_test_all().
Variable Documentation
char testnames[100][64]
Definition at line 11 of file msm4g_tests.c.
Referenced by msm4g_test_assert(), and msm4g_test_summary().
Boolean teststatus[100]
Definition at line 12 of file msm4g_tests.c.
Referenced by msm4g_test_assert(), msm4g_test_summary(), msm4g_unit_test_11(), msm4g_unit_test_12(), msm4g_unit_test_13(), msm4g_unit_test_14(), msm4g_unit_test_15(), msm4g_unit_test_16(), msm4g_unit_test_17(), msm4g_unit_test_18(), msm4g_unit_test_19(), msm4g_unit_test_20(), msm4g_unit_test_21(), msm4g_unit_test_22(), msm4g_unit_test_23(), msm4g_unit_test_24(), and msm4g_unit_test_9().
int testcount = 0
Definition at line 13 of file msm4g_tests.c.
Referenced by msm4g_test_assert(), and msm4g_test_summary().