MSM4G: msm4g_bases.c File Reference
msm4g_bases.c File Reference
#include "msm4g_bases.h"
Functions
static double cubic_hermite0 (double t)
static double cubic_hermite1 (double t)
static double cubic_hermite2 (double t)
static double cubic_hermite3 (double t)
static double cubic_bspline0 (double t)
static double cubic_bspline1 (double t)
static double cubic_bspline2 (double t)
static double cubic_bspline3 (double t)
double msm4g_bases_bspline (int k, double u)
Evaluates B-Spline bases.
double msm4g_bases_bsplineprime (int k, double u)
Evaluates the derivative B-Spline bases.
Variables
static const struct BaseFunction _CubicHermite = { 4, {cubic_hermite0, cubic_hermite1, cubic_hermite2, cubic_hermite3} }
static const struct BaseFunction _CubicBSpline = { 4, {cubic_bspline0, cubic_bspline1, cubic_bspline2, cubic_bspline3} }
const BaseFunction * CubicHermite = & _CubicHermite
const BaseFunction * CubicBSpline = & _CubicBSpline
Function Documentation
cubic_hermite0()
static double cubic_hermite0 (double t) static
Definition at line 3 of file msm4g_bases.c.
cubic_hermite1()
static double cubic_hermite1 (double t) static
Definition at line 4 of file msm4g_bases.c.
cubic_hermite2()
static double cubic_hermite2 (double t) static
Definition at line 5 of file msm4g_bases.c.
cubic_hermite3()
static double cubic_hermite3 (double t) static
Definition at line 6 of file msm4g_bases.c.
cubic_bspline0()
static double cubic_bspline0 (double t) static
Definition at line 8 of file msm4g_bases.c.
cubic_bspline1()
static double cubic_bspline1 (double t) static
Definition at line 9 of file msm4g_bases.c.
cubic_bspline2()
static double cubic_bspline2 (double t) static
Definition at line 10 of file msm4g_bases.c.
cubic_bspline3()
static double cubic_bspline3 (double t) static
Definition at line 11 of file msm4g_bases.c.
msm4g_bases_bspline()
double msm4g_bases_bspline (int k, double u)
Evaluates B-Spline bases.
Calculates the B-Spline bases of order k at any given point u. It uses the recursive definition given in Eq 7 in "The Journal of Chemical Physics 144, 114112 (2016); doi: 10.1063/1.4943868".
Todo:
Using the recursive definition is easy and appearently not too costly but it is one of the first places to look for if overall MSM has some performance issues.
Parameters
[in] k Order of B-Spline
[in] u Evaluation point
Returns
B-Spline of order k evaluated at point u
Definition at line 19 of file msm4g_bases.c.
References msm4g_bases_bspline().
Referenced by msm4g_anterpolation(), msm4g_bases_bspline(), msm4g_bases_bsplineprime(), msm4g_unit_test_13(), msm4g_util_calculate_c(), and msm4g_util_omegaprime().
msm4g_bases_bsplineprime()
double msm4g_bases_bsplineprime (int k, double u)
Evaluates the derivative B-Spline bases.
Calculates the derivative of B-Spline bases of order k at any given point u. It uses the recursive definition given in Section II.B.1 in "The Journal of Chemical Physics 144, 114112 (2016); doi: 10.1063/1.4943868".
Todo:
Like its non-derivative version, it also uses a recursive definition. So it is also one of the first places to look for if overall MSM has some performance issues.
Parameters
[in] k Order of B-Spline
[in] u Evaluation point
Returns
Derivative of B-Spline of order k evaluated at point u
Definition at line 32 of file msm4g_bases.c.
References msm4g_bases_bspline().
Referenced by msm4g_unit_test_13().
Variable Documentation
_CubicHermite
const struct BaseFunction _CubicHermite = { 4, {cubic_hermite0, cubic_hermite1, cubic_hermite2, cubic_hermite3} } static
Definition at line 13 of file msm4g_bases.c.
_CubicBSpline
const struct BaseFunction _CubicBSpline = { 4, {cubic_bspline0, cubic_bspline1, cubic_bspline2, cubic_bspline3} } static
Definition at line 14 of file msm4g_bases.c.
CubicHermite
const BaseFunction* CubicHermite = & _CubicHermite
Definition at line 16 of file msm4g_bases.c.
CubicBSpline
const BaseFunction* CubicBSpline = & _CubicBSpline
Definition at line 17 of file msm4g_bases.c.