MSM4G: msm4g_tests.h File Reference
msm4g_tests.h File Reference
The declarations of the test functions.
#include "msm4g_lib.h"
Functions
void msm4g_unit_test_all ()
Runs all tests.
Boolean msm4g_unit_test_1 ()
Checks the size() functionality of linked lists.
Boolean msm4g_unit_test_2 ()
Traversing the linked list from tail to head.
Boolean msm4g_unit_test_3 ()
Traversing the list from head to tail.
Boolean msm4g_unit_test_4 ()
Reading particle configurations from a text file.
Boolean msm4g_unit_test_5 ()
Creating a box surrounding the particles.
Boolean msm4g_unit_test_6 ()
Generating bins for the particles in eight.ini file.
Boolean msm4g_unit_test_7 ()
Testing Cantor pairing function.
Boolean msm4g_unit_test_8 ()
Testing smoothing functions.
Boolean msm4g_unit_test_9 ()
Short-range energy calculation test.
Boolean msm4g_unit_test_10 ()
Testing DenseGrid implementation.
Boolean msm4g_unit_test_11 ()
Testing anterpolation.
Boolean msm4g_unit_test_12 ()
Checks the correctness of Quasi-interpolation coefficients.
Boolean msm4g_unit_test_13 ()
Checks B-Spline implementation.
Boolean msm4g_unit_test_14 ()
Checks the implementation of even-powered softener.
Boolean msm4g_unit_test_15 ()
Checks short-range potential energy for periodic boundary.
Detailed Description
The declarations of the test functions.
The test functions are self-contained so they don't require inputs. They only return a boolean indicating the fate of the test. The test function msm4g_unit_test_all() runs all of the tests.
Definition in file msm4g_tests.h.
Function Documentation
msm4g_unit_test_all()
void msm4g_unit_test_all ()
Runs all tests.
All test functions are sequentiall run and their results are printed to standard output. If one of the tests is failed, then the corresponding test information is printed to the standard error.
Definition at line 11 of file msm4g_tests.c.
References msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_get(), msm4g_linkedlist_new(), msm4g_linkedlist_size(), msm4g_unit_test_1(), msm4g_unit_test_10(), msm4g_unit_test_11(), msm4g_unit_test_12(), msm4g_unit_test_13(), msm4g_unit_test_14(), msm4g_unit_test_15(), msm4g_unit_test_2(), msm4g_unit_test_3(), msm4g_unit_test_4(), msm4g_unit_test_5(), msm4g_unit_test_6(), msm4g_unit_test_7(), msm4g_unit_test_8(), and msm4g_unit_test_9().
Referenced by main().
msm4g_unit_test_1()
Boolean msm4g_unit_test_1 ()
Checks the size() functionality of linked lists.
Returns
true if the test is successful, false otherwise.
Definition at line 54 of file msm4g_tests.c.
References msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_linkedlist_size(), and msm4g_particle_reset().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_2()
Boolean msm4g_unit_test_2 ()
Traversing the linked list from tail to head.
Using the prev pointer element in the LinkedListElement one can travel from the tail element to the head.
Returns
true if the test is successful, false otherwise.
Definition at line 76 of file msm4g_tests.c.
References LinkedListElement::data, Particle::m, msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), LinkedListElement::prev, and LinkedList::tail.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_3()
Boolean msm4g_unit_test_3 ()
Traversing the list from head to tail.
Returns
true if the test is successful, false otherwise.
Definition at line 113 of file msm4g_tests.c.
References LinkedListElement::data, LinkedList::head, Particle::m, msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), and LinkedListElement::next.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_4()
Boolean msm4g_unit_test_4 ()
Reading particle configurations from a text file.
The masses, locations and velocities of three particles are read from eight.ini file and compared to the true values. If there is a slight variation, the test returns with fail.
Returns
true if the test is successful, false otherwise.
Definition at line 150 of file msm4g_tests.c.
References Particle::m, msm4g_linkedlist_destroy(), msm4g_linkedlist_get(), msm4g_particle_read(), msm4g_particle_reset(), Particle::r, Particle::v, and D3Vector::value.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_5()
Boolean msm4g_unit_test_5 ()
Creating a box surrounding the particles.
Given a collection of particles, this test determines a rectangular simulation box surrounding all of them and compares the result with the expected box. In this example, 10 random particles are created in unit 3D cube. Then the location of one of them is set to [-1,-2,-3]. Another one is set to [1,2,3]. Given this configuration the location, and the width of the box shoould be [-1,-2,-3] and [2,4,6] respectively. But then a 0.5 margin is also used to enlarge the box. Then the new width should be [3,6,9]. The location should also be shifted so that the there is a margin on both minus and plus axis. So the new location is [-1.5,-3,-4.5]. At the end of the test, the calculated location and width is compared with the expecteds.
Returns
true if the test is successful, false otherwise.
Definition at line 206 of file msm4g_tests.c.
References SimulationBox::location, msm4g_box_destroy(), msm4g_box_new(), msm4g_box_update(), msm4g_d3vector_daxpy(), msm4g_d3vector_norm(), msm4g_d3vector_set(), msm4g_linkedlist_add(), msm4g_linkedlist_destroy(), msm4g_linkedlist_new(), msm4g_particle_destroyarray(), msm4g_particle_rand(), Particle::r, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_6()
Boolean msm4g_unit_test_6 ()
Generating bins for the particles in eight.ini file.
The flow of this test is as follows:
Loading the particles from eight.ini file
Creating a simulation box around the particles with 0.5 extra margin
Generating the bins
30  +----------+----------+----------+     Bin Width: 10
|   |          |  4       |          |
|   |          |   5      |          |     Particle Location
|   |          |    6     |          |     -------- --------
|   |          |          |          |     1        [15,15, 5]
20  +----------+----------+----------+     2        [15,12, 5]
|   |          |          |          |     3        [29, 2,25]
|   |          |     1    |          |     4        [12,26, 5]
|   |          |          |          |     5        [13,25, 5]
|   |          |     2    |          |     6        [14,24, 5]
10  +----------+----------+----------+
|   |          |          |          |     Bins
|   |          |          |          |     ----
|   |          |          |          |     i j k   Particles Neighbor Bins
|   |          |          |         3|     - - -   --------- -------------
0   +----------+----------+----------+     1 1 0   1,2       [1,2,0]
                                           2 0 2   3         none
    0----------10---------20---------30    1 2 0   4,5,6     [1,1,0]
       i=0         i=1         i=2
Returns
true if the test is successful, false otherwise.
Definition at line 262 of file msm4g_tests.c.
References Bin::cantorindex, SimulationBox::location, msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_linkedlist_destroyWithData(), msm4g_linkedlist_get(), msm4g_linkedlist_size(), msm4g_particle_read(), Bin::neighbors, Bin::particles, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_7()
Boolean msm4g_unit_test_7 ()
Testing Cantor pairing function.
The test function is used to check the output of Cantor pairing function msm4g_math_cantor() applied to a 4x4 matrix. If the enumeration is not equal to the one below, the test returns false. The test also checks the output of msm4g_math_factorial() function for the integers, 0, 1, 2, 3, 4, and 5.
i/j j=0 j=1 j=2 j=4
i=0 0 1 3 6
i=1 2 4 7 11
i=2 5 8 12 17
i=3 9 13 18 24
Returns
true if the test is successful, false otherwise.
Definition at line 310 of file msm4g_tests.c.
References msm4g_math_cantor(), and msm4g_math_factorial().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_8()
Boolean msm4g_unit_test_8 ()
Testing smoothing functions.
Checks the implementation of the smoothing functions and their derivatives on p=0.0 and p=1.0; The \(\gamma \) functions tested are msm4g_smoothing_C1(), msm4g_smoothing_C2(), and msm4g_smoothing_C3().
Returns
true if the test is successful, false otherwise.
Definition at line 338 of file msm4g_tests.c.
References msm4g_smoothing_gama(), and msm4g_smoothing_gamaprime().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_9()
Boolean msm4g_unit_test_9 ()
Short-range energy calculation test.
The setup of the particles and the simulation box is the same with msm4g_unit_test_6(). This time short-range force and energy calculation is carried out.
The manually calculated short-range potential regarding to the setup is 1.51303181237454868855 which is compared to the calculated potential energy. If the relative error in the potential energy is greater than 1E-15, the test is failed.
Note
In this test, C1 gamma smoothing function msm4g_smoothing_C1() is used with cut-off parameter a=10.
Returns
true if the test is successful, false otherwise.
Definition at line 364 of file msm4g_tests.c.
References SimulationBox::location, msm4g_bin_destroy(), msm4g_bin_generate(), msm4g_force_short(), msm4g_linkedlist_destroyWithData(), msm4g_particle_read(), SimulationParameters::nu, SimulationParameters::periodic, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_10()
Boolean msm4g_unit_test_10 ()
Testing DenseGrid implementation.
This function tests the basic functionality of DenseGrid related functions.
Returns
true if the test is successful, false otherwise.
Definition at line 397 of file msm4g_tests.c.
References msm4g_grid_dense_new(), msm4g_grid_destroy(), AbstractGrid::reset, and AbstractGrid::setElement.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_11()
Boolean msm4g_unit_test_11 ()
Testing anterpolation.
In this test, 8 unit mass particles are created on the following locations. The degree of base polynomials is set to p=3. Then a simulation box is created with margin=0. Since p=3, an extra padding is added around the boundary as shown in the following figure. Then the anterpolation is run. Since Hermite nodal basis functions are used in the anterpolation, the grid masses on the 8 interior nodes will be 1, and the rest should be zero.
30  +----------+----------+----------+     Lattice spacing (h): 10
|   |          |          |          |
|   |          |          |          |     Particle Location
|   |          |          |          |     -------- --------
|   |          |          |          |     1        [10,10,10]
20  +----------O----------O----------+     2        [10,10,20]
|   |          |          |          |     3        [10,20,10]
|   |          |          |          |     4        [10,20,20]
|   |          |          |          |     5        [20,10,10]
|   |          |          |          |     6        [20,10,20]
10  +----------O----------O----------+     7        [20,20,10]
|   |          |          |          |     8        [20,20,20]
|   |          |          |          |
|   |          |          |          |
|   |          |          |          |
0   +----------+----------+----------+
    0----------10---------20---------30
Returns
true if the test is successful, false otherwise.
Definition at line 422 of file msm4g_tests.c.
References CubicBSpline, AbstractGrid::getElement, msm4g_anterpolation(), msm4g_box_destroy(), msm4g_box_new(), msm4g_box_update(), msm4g_grid_dense_new(), msm4g_grid_destroy(), msm4g_linkedlist_add(), msm4g_linkedlist_destroyWithData(), msm4g_linkedlist_new(), msm4g_particle_new(), AbstractGrid::reset, D3Vector::value, and SimulationBox::width.
Referenced by msm4g_unit_test_all().
msm4g_unit_test_12()
Boolean msm4g_unit_test_12 ()
Checks the correctness of Quasi-interpolation coefficients.
Checks the accuracy of quasi-interpolation coefficients explained in "The Journal of Chemical Physics 144, 114112 (2016); doi: 10.1063/1.4943868" The test calculates the coefficients for Cubic and Quintic B-Spline cases and compare them to the ones published in the Table I of the same article.
Returns
true if the test is successful, false otherwise.
Definition at line 461 of file msm4g_tests.c.
References false, and msm4g_util_omegaprime().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_13()
Boolean msm4g_unit_test_13 ()
Checks B-Spline implementation.
To check the implementation, I compare the results of MSM implementation to the ones I previously obtained by using Mathematica'a BSpline function for which the domain is always [0,1] in contrast to [0,k] in MSM. The test is successful if the following relation holds for points u = k*i/8 where i=0,...,8 and k is either 4 (cubic) or 6 (quintic).
 MSM Implementation                  Mathematica
 ------------------                  -----------
 msm4g_bases_bspline     (k, u)   =    BSpline[k-1,u/k]
 msm4g_bases_bsplineprime(k, u)   =  D[BSpline[k-1,u/k]]/k
 where u is in [0,k] and k is the order of B-Spline.
Returns
true if the test is successful, false otherwise.
Definition at line 482 of file msm4g_tests.c.
References msm4g_bases_bspline(), and msm4g_bases_bsplineprime().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_14()
Boolean msm4g_unit_test_14 ()
Checks the implementation of even-powered softener.
This test evaluates the softener and its derivative on \(\rho = \{0,1/2,1,3/2\} \) for \(\nu=\{2,3,4,5,6\} \) and compare the results with the hand-evaluated values.
Returns
true if the test is successful, false otherwise
Definition at line 509 of file msm4g_tests.c.
References msm4g_smoothing_gama(), and msm4g_smoothing_gamaprime().
Referenced by msm4g_unit_test_all().
msm4g_unit_test_15()
Boolean msm4g_unit_test_15 ()
Checks short-range potential energy for periodic boundary.
It calculates the short-range potential energy and compares it to the one computed with reference periodic MSM implementation.
Returns
true if the test is successful, false otherwise
Definition at line 535 of file msm4g_tests.c.
References msm4g_simulation_delete(), and msm4g_simulation_new().
Referenced by msm4g_unit_test_all().