MSM4G: msm4g_bases.h File Reference
msm4g_bases.h File Reference
#include <stdio.h>
Data Structures
struct BaseFunction
Macros
#define MAX_POLY_DEGREE 20
Typedefs
typedef struct BaseFunction BaseFunction
Functions
double msm4g_bases_bspline (int k, double u)
Evaluates B-Spline bases.
double msm4g_bases_bsplineprime (int k, double u)
Evaluates the derivative B-Spline bases.
Variables
const BaseFunction * CubicHermite
const BaseFunction * CubicBSpline
Macro Definition Documentation
MAX_POLY_DEGREE
#define MAX_POLY_DEGREE 20
Definition at line 6 of file msm4g_bases.h.
Referenced by msm4g_anterpolation().
Typedef Documentation
BaseFunction
typedef struct BaseFunction BaseFunction
Function Documentation
msm4g_bases_bspline()
double msm4g_bases_bspline (int k, double u)
Evaluates B-Spline bases.
Calculates the B-Spline bases of order k at any given point u. It uses the recursive definition given in Eq 7 in "The Journal of Chemical Physics 144, 114112 (2016); doi: 10.1063/1.4943868".
Todo:
Using the recursive definition is easy and appearently not too costly but it is one of the first places to look for if overall MSM has some performance issues.
Parameters
[in] k Order of B-Spline
[in] u Evaluation point
Returns
B-Spline of order k evaluated at point u
Definition at line 19 of file msm4g_bases.c.
References msm4g_bases_bspline().
Referenced by msm4g_anterpolation(), msm4g_bases_bspline(), msm4g_bases_bsplineprime(), msm4g_unit_test_13(), msm4g_util_calculate_c(), and msm4g_util_omegaprime().
msm4g_bases_bsplineprime()
double msm4g_bases_bsplineprime (int k, double u)
Evaluates the derivative B-Spline bases.
Calculates the derivative of B-Spline bases of order k at any given point u. It uses the recursive definition given in Section II.B.1 in "The Journal of Chemical Physics 144, 114112 (2016); doi: 10.1063/1.4943868".
Todo:
Like its non-derivative version, it also uses a recursive definition. So it is also one of the first places to look for if overall MSM has some performance issues.
Parameters
[in] k Order of B-Spline
[in] u Evaluation point
Returns
Derivative of B-Spline of order k evaluated at point u
Definition at line 32 of file msm4g_bases.c.
References msm4g_bases_bspline().
Referenced by msm4g_unit_test_13().
Variable Documentation
CubicHermite
const BaseFunction* CubicHermite
Definition at line 16 of file msm4g_bases.c.
CubicBSpline
const BaseFunction* CubicBSpline
Definition at line 17 of file msm4g_bases.c.