MSM4G: AbstractGrid Struct Reference
AbstractGrid Struct Reference
An abstract 3-dimensional grid structure.
#include <msm4g_types.h>
Data Fields
double hx
The lattice spacing.
double hy
The lattice spacing.
double hz
The lattice spacing.
int nx
The number of nodes along x-axis.
int ny
The number of nodes along y-axis.
int nz
The number of nodes along z-axis.
struct AbstractGrid *(* constructor)(int nx, int ny, int nz, double hx, double hy, double hz)
A pointer to the grid constructor.
void(* destructor)(struct AbstractGrid **grid)
A pointer to the grid destructor.
void(* setElement)(struct AbstractGrid *grid, int i, int j, int k, double value)
A pointer to the setter function.
double(* getElement)(struct AbstractGrid *grid, int i, int j, int k)
A pointer to the function prototype for getting a single element.
void(* reset)(struct AbstractGrid *grid, double value)
A pointer to the reset function.
double(* innerProduct)(struct AbstractGrid *grid1, struct AbstractGrid *grid2)
A pointer to a prototype of inner production function.
void(* add)(struct AbstractGrid *grid1, struct AbstractGrid *grid2)
A pointer to grid addition function The grid implementation should define a function to add the contents of grid2 to grid1.
double(* sum)(struct AbstractGrid *grid)
Sum of grid elements.
Detailed Description
An abstract 3-dimensional grid structure.
This AbstractGrid structure defines the interfaces that the grid implementations should follow. Its main aim is to hide the details of different grid implementations as much as possible and increase the code reuse.
Independent from the implementation, a 3D simulation domain is repeatedly divided into grids whose nodes are stored is internal data structures of the implementation grid object such as DenseGrid or SparseGrid. The visualization of an AbstractGrid is shown below. In this 2D example (3D case is the straightforward generalization) there are nx and ny grid nodes in each axis and the lattice spacing is h.
(ny-1)*h +=======+=======+=======+=======+
         |       |       |       |       |
.        |       |       |       |       |
.        |       |       |       |       |
.        +=======+=======+=======+=======+
         |       |       |       |       |
         |       |       |       |       |
         |       |       |       |       |
h        +=======+=======+=======+=======+
         |       |       |       |       |
         |       |       |       |       |
         |       |       |       |       |
0        +=======+=======+=======+=======+
         0       h       2h     ....  (nx-1)*h
In order to use AbstractGrid in the code, one should first use a constructor designed for an implementation. After that, the methods msm4g_grid_xxx can be be used without dealing with details regarding the grid implementation.
  int nx=10;
  int ny=10;
  int nz=10;
  double h=1.0;
  double element;
  AsbtractGrid *grid;
  grid = msm4g_dense_grid_new(nx,ny,nz,h);
  grid->reset(grid, 0.0);
  grid->setElement(grid,3,4,5,10.0);
  element = grid->getElement(grid,3,4,5);
  msm4g_grid_destroy(&grid);
*
Definition at line 272 of file msm4g_types.h.
Field Documentation
double hx
The lattice spacing.
The distance between the grid nodes along x-axis.
Definition at line 277 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), and msm4g_stencil().
double hy
The lattice spacing.
The distance between the grid nodes along y-axis.
Definition at line 283 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), and msm4g_stencil().
double hz
The lattice spacing.
The distance between the grid nodes along z-axis.
Definition at line 289 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), and msm4g_stencil().
int nx
The number of nodes along x-axis.
This member defines the number of nodes in the x-axis. Hence the number of boxes aling the axis will nx-1. The coordinate of the last node will be (nx-1)*h.
Definition at line 297 of file msm4g_types.h.
Referenced by msm4g_grid_dense_add(), msm4g_grid_dense_getElement(), msm4g_grid_dense_innerProduct(), msm4g_grid_dense_new(), msm4g_grid_dense_reset(), msm4g_grid_dense_setElement(), msm4g_grid_dense_sum(), msm4g_grid_potential(), msm4g_grid_print(), msm4g_prolongation(), msm4g_restriction(), msm4g_simulation_save(), msm4g_stencil(), msm4g_unit_test_11(), msm4g_unit_test_18(), and msm4g_unit_test_19().
int ny
The number of nodes along y-axis.
This member defines the number of nodes in the y-axis. Hence the number of boxes aling the axis will ny-1. The coordinate of the last node will be (ny-1)*h.
Definition at line 305 of file msm4g_types.h.
Referenced by msm4g_grid_dense_add(), msm4g_grid_dense_getElement(), msm4g_grid_dense_innerProduct(), msm4g_grid_dense_new(), msm4g_grid_dense_reset(), msm4g_grid_dense_setElement(), msm4g_grid_dense_sum(), msm4g_grid_potential(), msm4g_grid_print(), msm4g_prolongation(), msm4g_restriction(), msm4g_stencil(), msm4g_unit_test_11(), msm4g_unit_test_18(), and msm4g_unit_test_19().
int nz
The number of nodes along z-axis.
This member defines the number of nodes in the z-axis. Hence the number of boxes aling the axis will nz-1. The coordinate of the last node will be (nz-1)*h.
Definition at line 313 of file msm4g_types.h.
Referenced by msm4g_grid_dense_add(), msm4g_grid_dense_innerProduct(), msm4g_grid_dense_new(), msm4g_grid_dense_reset(), msm4g_grid_dense_sum(), msm4g_grid_potential(), msm4g_grid_print(), msm4g_prolongation(), msm4g_restriction(), msm4g_stencil(), msm4g_unit_test_11(), msm4g_unit_test_18(), and msm4g_unit_test_19().
struct AbstractGrid*(* constructor)(int nx, int ny, int nz, double hx, double hy, double hz)
A pointer to the grid constructor.
This function pointer determines the prototype of a grid constructor which every grid implementations should create a one.
Definition at line 321 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new().
void(* destructor)(struct AbstractGrid **grid)
A pointer to the grid destructor.
Every grid implementations should define a function satisfying this destructor prototype. But the implementations should only deallocate their internal data structures.
Definition at line 330 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new().
void(* setElement)(struct AbstractGrid *grid, int i, int j, int k, double value)
A pointer to the setter function.
Every grid implementation should provide a setter function to set a specific value to the given coordinates.
Definition at line 338 of file msm4g_types.h.
Referenced by msm4g_anterpolation(), msm4g_grid_dense_new(), msm4g_prolongation(), msm4g_restriction(), msm4g_stencil(), and msm4g_unit_test_10().
double(* getElement)(struct AbstractGrid *grid, int i, int j, int k)
A pointer to the function prototype for getting a single element.
The grid implementations should implement a function complying to this prototype.
Definition at line 346 of file msm4g_types.h.
Referenced by msm4g_anterpolation(), msm4g_grid_dense_new(), msm4g_grid_print(), msm4g_interpolation(), msm4g_prolongation(), msm4g_restriction(), msm4g_unit_test_11(), msm4g_unit_test_16(), msm4g_unit_test_18(), and msm4g_unit_test_19().
void(* reset)(struct AbstractGrid *grid, double value)
A pointer to the reset function.
Sets all elements in the grid to the given value.
Definition at line 352 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), and msm4g_unit_test_10().
double(* innerProduct)(struct AbstractGrid *grid1, struct AbstractGrid *grid2)
A pointer to a prototype of inner production function.
The grid implementations should define a function to calculate inner product of two grids.
Definition at line 359 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), msm4g_potential_energy(), msm4g_unit_test_18(), and msm4g_unit_test_19().
void(* add)(struct AbstractGrid *grid1, struct AbstractGrid *grid2)
A pointer to grid addition function The grid implementation should define a function to add the contents of grid2 to grid1.
Definition at line 366 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new(), msm4g_prolongation(), and msm4g_simulation_run().
double(* sum)(struct AbstractGrid *grid)
Sum of grid elements.
Definition at line 370 of file msm4g_types.h.
Referenced by msm4g_grid_dense_new().
The documentation for this struct was generated from the following file:
msm4g_types.h